### ISSUE TITLE
Less generic AppCenter icon [$100 awarded]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#1]
The colored square with an arrow seems pretty generic, maybe you could come up with something more unique

> **Daniel Fore (danrabbit)**:
> I'm going to defer this from Loki. I've updated the AppCenter slightly, but I think we want to preserve a major brand change for a major feature that probably won't come this cycle.

---

Originally filed by [Alexander Wilms](https://launchpad.net/~alexander-wilms) on [Launchpad](https://bugs.launchpad.net/elementaryicons/+bug/1091587).
##

**Comment by danrabbit** [comment]
https://www.bountysource.com/issues/28934372-less-generic-appcenter-icon

**Comment by cheat117** [comment]
Hey guys, is this an icon bounty or a code bounty?

Is there somewhere with the requirements of icons that I can review?

**Comment by donadigo** [comment]
This is an icon bounty, you can read our HIG for icons here:
https://elementary.io/pl/docs/human-interface-guidelines#iconography

**Comment by cheat117** [comment]
Thanks!

**Comment by danrabbit** [comment]
Hey @cheat117 please note that this issue is already assigned to someone else and is marked as in progress.
