### ISSUE TITLE
Help in packaging our app icon

### ISSUE THREAD

**Issue by nuttyartist** [elementary/icons#101]
Hi there,

I'm part of the people that works on [Notes](https://github.com/nuttyartist/notes). So we have the .svg icon for our app but we need help in handling its packaging, so I thought you guys might help.
This is the .svg, made by @KevDoy: [notes.zip](https://github.com/elementary/icons/files/428304/notes.zip)

We need help in these areas:

- Extracting to all the different resolutions, including the @2x thing.
- How to package the app so Elementary and other Ubuntu distros will use all the different resolutions (including the @2x).

Thanks,

Notes team

**Comment by snwh** [comment]
The **best** practice for creating icons for a Linux app is to provide an icon for each of the standard sizes and ship those; an app should provide a versions of their icon at 16x16, 22x22 & 24x24 (usually the same icon but with 1px extra of padding), 32x32, 48x48, and a high resolution version (usually 256x256 or 512x512) or it can be a scalable asset.

 - There is no "extraction" process. HiDPi icons (@2x) are extra assets that are pixel doubled versions, e.g. a 32x32@2x icon is the 32x32 icon at twice the scale.

 - To have your app's icons be read by the OS, all assets should be placed in to `/usr/share/icons/hicolor/*/apps/`, where * is the resolution of the asset.

That being said, you only have a single icon asset for Notes, installing it in `/usr/share/icons/hicolor/scalable/apps/` would suffice for all distros &ndash;if you don't provide any other icon assets, this is all you need to do.

**Comment by nuttyartist** [comment]
1. Can you explain how can I create all the different resolutions, including the HiDPi icons (@2x) using Inkscape from our .svg file?
2. Alright, thanks for that.

**Comment by snwh** [comment]
@nuttyartist well, the proper route would be to have someone draw all those assets. But like I said, if you have no intention of adding new assets tailored to all those specific sizes, installing your scalable icon (the .svg) into `/usr/share/icons/hicolor/scalable/apps/` would suffice.

**Comment by snwh** [comment]
Marked as "Invalid" and closed since this isn't a bug related to the icon theme itself. Please, feel free to continue the discussion.

**Comment by nuttyartist** [comment]
@snwh that's ok, but I would still like to know how to do that if you know. It will also help in making it work on Windows and Mac where there isn't a `scalable` directory.

**Comment by SHENOISZ** [comment]
Look this

https://github.com/SHENOISZ/anieplayer/blob/master/applications/anieplayer.desktop

https://github.com/SHENOISZ/anieplayer

**Comment by laberba** [comment]
Sorry @snwh, but how are @2x svg icons displayed since icons are just place according to sizes?

**Comment by snwh** [comment]
@laberba well, we have a blog post on the matter: http://blog.elementary.io/post/124193007916/whats-up-with-hidpi-icons

**Comment by nuttyartist** [comment]
@snwh, I'm a pretty noob in that area. Can you explain to me how can I generate different icons from my .svg in Inkscape (Including @2x ones)?
