### ISSUE TITLE
input-keyboard-symbolic too small when used at LARGE_TOOLBAR size

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#1016]
Like in the installer

![Screenshot from 2021-03-05 13-05-01](https://user-images.githubusercontent.com/611168/110168364-5050f400-7db4-11eb-9d68-a110c58ad428.png)

**Comment by danrabbit** [comment]
I imagine we should probably gresource icons specifically for that purpose there. This icon is that size for the panel, which make should also be gresourced instead
