### ISSUE TITLE
Redesign error icons

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#102]
The current error icon is kind of this traditional bar thingy we inherited from Tango or something but it's not very nice looking.

Stumbled across this and it looks a bit nicer as the symbolic variant

![ui-kit](https://cloud.githubusercontent.com/assets/7277719/17832842/4d9d9230-66c2-11e6-9651-78d7c03f2d36.png)

**Comment by laberba** [comment]
:+1:

**Comment by danrabbit** [comment]
Please don't leave spam comments. There is a reaction button on the post if you'd like to leave a reaction

**Comment by laberba** [comment]
Now that's not a nice way to educate people.

http://www.urbandictionary.com/define.php?term=spamming: "A refined art created by today's youth. Spammers do not follow rules, they don't obey the Administrators or Moderators or unfair rules. They fight for freedom and ...". 
Don't use  **Spam**  lightly (https://en.wikipedia.org/wiki/Spamming)

**Comment by snwh** [comment]
@danrabbit do we want to update the coloured version with the ! motif?

**Comment by danrabbit** [comment]
@snwh Yeah I think they should match

**Comment by danrabbit** [comment]
Closed by #103
