### ISSUE TITLE
Flatpak bundles use archive icon

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#1021]
## Problem

Flatpak bundles (extension `.flatpak`, media type `application/vnd.flatpak`) appear as archives in Files.

![Screenshot from 2021-04-14 13-56-31](https://user-images.githubusercontent.com/611168/114770944-40202300-9d29-11eb-803a-887ab2d63717.png)

## Proposal

Either symlink to the flatpakref icon (https://github.com/elementary/icons/pull/653) or provide a new Flatpak bundle icon. 

## Prior Art

We use a mediatype icon for .deb files (see screenshot above), so symlinking to the flatpakref icon would be consistent and the easiest here.

**Comment by danrabbit** [comment]
Yeah I wonder if it would make sense to make an archive icon with the flatpak logo on it?

**Comment by cassidyjames** [comment]
@danrabbit could do, or just a symlink honestly—we use a mediatype icon for .deb files even though they could be standalone binary packages versus a manifest file.

**Comment by danrabbit** [comment]
Playing with the idea of some package icons:

![Screenshot from 2021-04-14 13 20 32](https://user-images.githubusercontent.com/7277719/114774171-bcfcce00-9d24-11eb-8cb9-80e5c650a950.png)

**Comment by hanaral** [comment]
I know this may sound a little much but how about using some kind of subtle elementary branding on detected 'elementary' app packages and using the generic white ones for flatpak and deb?
(although I'd much rather deb be removed entirely eventually but that's another convo. entirely)

**Comment by cassidyjames** [comment]
@hanaral we don't expect users to regularly download bundles or refs for elementary apps anyway, so I don't think that's worthwhile; plus an experimental or modified build of an app shouldn't look any more "official" than any other Flatpak imho.

**Comment by Henryws** [comment]
> Playing with the idea of some package icons:
> 
> ![Screenshot from 2021-04-14 13 20 32](https://user-images.githubusercontent.com/7277719/114774171-bcfcce00-9d24-11eb-8cb9-80e5c650a950.png)

I quite like the bottom left because of the nice contrast

**Comment by ChildishGiant** [comment]
I was coming to suggest this, any reason this hasn't been implemented? The icons Dani made look great!
