### ISSUE TITLE
Generate cursors OS agnostic

### ISSUE THREAD

**Issue by albfan** [elementary/icons#1026]
## Problem
cursor generation depends on xcursorgen, heavily dependant on x11 (linux only). There's an alternative that generates cursor based on python, used by adwaita theme: 

- https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/40.0/src/cursors/anicursorgen.py 
- https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/40.0/src/cursors/pngs/make-w32.sh#L3

Input files are the same `.in`

## Proposal

Replace `xcursorgen` with `anicursorgen.py`

## Prior Art

Adwaita gtk theme

This will fix elementary icon theme for msys2 (windows): https://github.com/msys2/MINGW-packages/pull/8505#issuecomment-831351520

**Comment by danrabbit** [comment]
As explained in the README, these icons are for elementary OS. I'm not really interested in maintaining a script for generating cursors in this repo. If this script becomes packaged then I would accept a PR to change out the dependency, but I really don't have any interest in doing work for Windows

**Comment by albfan** [comment]
@jbicha probably can help to package for ubuntu. I contact @lrn about migrated script used here https://github.com/msys2/MINGW-packages/pull/8575
