### ISSUE TITLE
[Mouse cursor] 'Move' cursor should not be used for scrolling

### ISSUE THREAD

**Issue by kdwk** [elementary/icons#1037]
## What Happened

When scrolling in Gtk apps, the cursor is changed to the 'move' cursor with a black dot in the center and four black triangles surrounding it. That cursor is typically associated with autoscroll in web browsers, and using it when scrolling will result in a inconsistency with browsers since the cursor remains unchanged when scrolling in browsers.

## Expected Behavior

The cursor remains unchanged when scrolling in Gtk apps

## Steps to Reproduce

1. Scroll in a Gtk app

## Platform Information

![Screenshot from 2021-07-14 10-55-34](https://user-images.githubusercontent.com/39268094/126252366-f115d204-7734-4867-a67c-ac2c8eb84f23.png)

**Comment by danirabbit** [comment]
I believe this has been fixed. I can't reproduce this with latest icons
