### ISSUE TITLE
Consider making wifi button bigger

### ISSUE THREAD

**Issue by D0J0P** [elementary/icons#1040]
## Problem

ref #1004 

If you draw a line across the top and bottom of the wingpanel indicators, the wifi icon looks noticeably smaller.

![108894945-cf317a00-75c7-11eb-9e55-a55dacb4f067 (2)](https://user-images.githubusercontent.com/19495660/131588916-91fc2d17-49a2-47db-8964-559976436f78.png)

Kinda looks visually smaller in the popover too compared to the radio button and title

![Screenshot from 2021-08-31 19-09-54](https://user-images.githubusercontent.com/19495660/131589226-59157855-b6ef-4a9e-91f7-7ddb6e97a329.png)

## Proposal

Make it a bit bigger

## Prior Art

ios 14's indicators look nice:
![Screenshot from 2021-08-31 19 40 23](https://user-images.githubusercontent.com/19495660/131589417-465d1c39-cb21-4826-856c-ed9a9474c06c.png)

MacOS Big Sur's indicators look very nice:

![Screenshot from 2021-08-31 19 42 40](https://user-images.githubusercontent.com/19495660/131589592-fe9c9784-927b-4972-8c91-5dbf096c348e.png)

**Comment by waldyrious** [comment]
Just for the record, this seems to have been the same issue as #800.
