### ISSUE TITLE
[Mouse cursor] Use larger icons for consequence of drag-and-drop actions

### ISSUE THREAD

**Issue by kdwk** [elementary/icons#1044]
### Problem

![Screenshot from 2021-10-01 19 17 55](https://user-images.githubusercontent.com/39268094/135612529-e39e86d2-f840-4dc2-9b8e-4649faf173b5.png)

The little 'link' icon beside the cursor that indicates the nature of the action -- create a link -- is inconspicuous and easy to miss. This creates confusion when the drag-and-drop action does something unexpected, as the consequence of the drag-and-drop action was never explained properly to the user

### Proposal

Create new cursors for drag-and-drop actions such that the consequence of the action is more prominent in the cursor design. 

### Prior Art (Optional)

[Apple macOS Human Interface Guidelines -- Cursors](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/mouse-and-trackpad/#pointers)

![Screenshot from 2021-10-01 19-26-01](https://user-images.githubusercontent.com/39268094/135612445-43ce36ed-7503-475b-b766-203fd1b03eb4.png)
![Screenshot from 2021-10-01 19-26-18](https://user-images.githubusercontent.com/39268094/135612446-7efa8d64-ac3c-4b1a-887f-ff430bd79a31.png)
![Screenshot from 2021-10-01 19-26-23](https://user-images.githubusercontent.com/39268094/135612449-a7082951-2153-4c7c-a0ab-797a3574495e.png)
![Screenshot from 2021-10-01 19-26-38](https://user-images.githubusercontent.com/39268094/135612453-22046e59-7508-4727-94cf-f8e06b95e2ac.png)

**Comment by danirabbit** [comment]
Fixed in #1250
