### ISSUE TITLE
Icons for show/hide password

### ISSUE THREAD

**Issue by dar5hak** [elementary/icons#1060]
### What?

A pair of icons which may be used to toggle showing a password in plain text. They could be symbolic only.

### Why?

Currently, for [Obliviate](https://appcenter.elementary.io/com.github.elfenware.obliviate), I use `image-red-eye-symbolic` (which is an open eye) inside a toggle button. But I am unsure about this choice, because that icon is meant for photo editing and has nothing to do with passwords.

Rather than me doing my own thing, it might be better to have these in the platform, because this scenario might come up anywhere there's a password entry. Cc @ChildishGiant.

### Design

The most common metaphor for a password “shown” is a human eye, and that for a password obfuscated is the same eye but closed and/or slashed. There may be other ways to represent this, but I'm not aware of any.

**Comment by dar5hak** [comment]
Maybe a stretch, but I can imagine this being even more useful as a Granite widget that extends Gtk.Entry and has this built-in, with the icon _inside_ the entry rectangle. Let me know your thoughts.

**Comment by danrabbit** [comment]
GTK4 has a password entry widget with this feature by default. We should find out what icon names are being used there

**Comment by dar5hak** [comment]
Awesome. I checked the source code: it uses [`eye-open-negative-filled-symbolic`](https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gtk/gtkpasswordentry.c#L172) and [`eye-not-looking-symbolic`](https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gtk/gtkpasswordentry.c#L177).

**Comment by danrabbit** [comment]
Wow those are some icon names lol. Thanks for looking them up!

**Comment by dar5hak** [comment]
Oddly, there is nothing with those names in the [Adwaita icon theme repo](https://gitlab.gnome.org/GNOME/adwaita-icon-theme). Not in the default branch at least.
