### ISSUE TITLE
Make more use of color in cursors

### ISSUE THREAD

**Issue by danirabbit** [elementary/icons#1065]
### Problem

Colors are historically very monochrome, but we could be a lot more expressive with color

### Proposal

Find ways to integrate color into cursors, maybe even accent colors?

### Prior Art (Optional)

https://github.com/ful1e5/Bibata_Cursor

**Comment by input-variable** [comment]
Hey! First-time contributor here, decided to dip my toes in the water and take a crack at this. 

![image](https://user-images.githubusercontent.com/11876024/147427743-46830c9b-d131-4f3f-b2b9-14fc1f1e4799.png)

Straying away from the proposal a bit, I focused on applying accent colours to the cursors. First, I tried applying a gradient fill on the left pointer (accent 700 -> 500). They look okay but I'm not too sure how they'll behave in terms of contrast/accessibility so further testing is needed.

I also mirrored the 700 -> 500 gradient on some of the other cursors. For the pencil cursor, I didn't apply a gradient for the base colour (keeping it in line with the original). Instead, I opted for the 700 accent variant over the 500 as the highlight added some brightness.

The shadows might be a good place to add an accent colour but once again, I'm not too sure how that might play out contrast-wise. 

![image](https://user-images.githubusercontent.com/11876024/147429721-985d668a-00ae-420b-a925-26d0f5292537.png)

I've also noticed that if accent colours are used for the modifier then a problem arises with symbols such as "copy" and "no-drop". By using the same accent colour for the fill of the small circle, we lose the effect of the original colour but in return gain a more visually cohesive style.  In the image above, I've presented four different combinations of the "copy" cursor in three different colours. The text above shows the fill of the circle for the entire column.

![image](https://user-images.githubusercontent.com/11876024/147429279-4c909282-2732-4334-ac9d-af6f771023e3.png)

Going back to the proposal, I added some more features to the pencil cursor and gave it colours that represented its real-world counterpart. More abstract cursors like the arrows/grab could potentially share one colour in a set (see below).

![image](https://user-images.githubusercontent.com/11876024/147430368-8c782a8d-4577-4916-9ae9-73629268730c.png)

If you have any questions/feedback, let me know. Hope this could help!

**Comment by danrabbit** [comment]
Hey @nakotami thanks for exploring this! I think I'm more in favor of the direction of using consistent colors for like cursor families or modifiers or things like what you've done with the pencil icon, rather than focusing on recoloring the cursor body itself.

I'd like to get away from cursors being a single color, and like you saw with modifiers it's more useful for those things to be a different color from the body of the cursor so they can convey meaning through their color

**Comment by wpkelso** [comment]
Did some explorations of `watch`, excluding any considerations for it's `ptr` variant.
![image](https://github.com/elementary/icons/assets/11094688/332edc51-feb9-4a63-8b49-5632c982dd50)

The first row is just each accent color applied to the existing cursor from 500→300, bottom→top. Every other row is an exploration of a different direction that the icon could go in, primarily focused around a rainbow coloration. Almost all of the animations have only been keyframed, not inbetweened (Only exception is row 3).

**Comment by danirabbit** [comment]
I think row 4 is my favorite :)

**Comment by wpkelso** [comment]
![image](https://github.com/elementary/icons/assets/11094688/8612dacd-8d72-41b4-b384-bcbec57c5778)

I took row 4 and explored it a little more, and I think I'm most partial to Md/Spinning Rainbow from these options.

![image](https://github.com/elementary/icons/assets/11094688/7dfce0d1-9545-43c2-a4fd-a21a074d773e)

I also played around with it in greyscale, and it seems like it will work better, more consistently than the "Chasing tail" option would.

**Comment by wpkelso** [comment]
Switching gears a little,

> From #1248 
>
> What do you think about putting all the symbols for dnd-cursors on a colored circle like `dnd-copy` is? Some of these symbols are a bit harder to see in these versions. For example this feels like a clear step back for legibility:
> 
> ![Screenshot from 2024-03-21 11 55 13](https://private-user-images.githubusercontent.com/7277719/315587175-19bc24e7-9f6a-4e75-824f-0c8c276aa23e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NDk0NjUsIm5iZiI6MTcxMjk0OTE2NSwicGF0aCI6Ii83Mjc3NzE5LzMxNTU4NzE3NS0xOWJjMjRlNy05ZjZhLTRlNzUtODI0Zi0wYzhjMjc2YWEyM2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTkxMjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTE1NmJhMzQwY2I4NTM2MjBjYjc0MTgwOTk1NzYxM2ZiMTQ2MjE2YWU3M2M4NTY1Y2IwMDk1NzAxYTI3MmQ0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.F8hr4zGEu_2NiSwqLXuMBDgZEHWm_uE5wPiffQQbbgo)
> 

(I'm moving this here given a lot more design work is needed before that PR is ready for full review. Lmk if it would be better to move things like this back to the PR.)

![image](https://github.com/elementary/icons/assets/11094688/c9965dda-c1c3-45e9-a436-f4be2cd3187b)

I was running into some issue maintaining the legibility of shapes while squeezing them into such minuscule circles, so I fattened the circles a bit. I think it would be natural for modified pointers to follow suit (`copy`, `link`) with this circle enlargement and language change, but I don't know whether it would be appropriate for `circle` and `no-drop` to follow the language established here as well, i.e. for `no-drop`

![image](https://github.com/elementary/icons/assets/11094688/16bcc85e-1cbc-40ed-9900-332f7cc138e4)

**Comment by danirabbit** [comment]
I think we can consider this fixed? There are a few cursors that are still monochrome but I think we can explore those as individual new issues maybe. Badges are now all colorful, and we have great new waiting cursors. We dropped cursors that aren't supported by the CSS spec so things like the pencil cursor are gone now
