### ISSUE TITLE
Missing selection-mode-symbolic

### ISSUE THREAD

**Issue by danirabbit** [elementary/icons#1142]
### What Happened?

The icon `selection-mode-symbolic` is missing in GNOME Builder and is likely used in other GNOME apps

### Steps to Reproduce

![Screenshot from 2022-10-26 10 26 54](https://user-images.githubusercontent.com/7277719/198095050-1d7c8407-213a-4f33-bd7d-7313ff7b3e44.png)

### Expected Behavior

https://github.com/GNOME/adwaita-icon-theme/blob/master/Adwaita/scalable/actions/selection-mode-symbolic.svg

### OS Version

7.x (Early Access)

### Software Version

Compiled from git

**Comment by wpkelso** [comment]
Fixed in #1185 

(The reference is also now at https://github.com/GNOME/adwaita-icon-theme/blob/master/Adwaita/symbolic/actions/selection-mode-symbolic.svg)
