### ISSUE TITLE
system-software-install

### ISSUE THREAD

**Issue by danirabbit** [elementary/icons#1151]
This is currently using the AppCenter icon, but we should make sure we're shipping the branded AppCenter icon with AppCenter and use a generic software install app icon here. This could be used for installing system packages/extensions that aren't related to appcenter like codecs or langpacks or something else

**Comment by wpkelso** [comment]
Would riffing off the building idea from AppCenter be appropriate here, or is that more core to AppCenter's branding and thus should be kept separate in this case? I could see a warehouse or a library working nicely alongside AppCenter, but I'm afraid it might not generalize well.

**Comment by danirabbit** [comment]
Another possibly interesting one is like a delivery truck being the thing that brings you packages

**Comment by wpkelso** [comment]
Unless I'm misunderstanding the use case of `system-software-update`, I think the two ideas could work in tandem for this and #1150 , where you have some warehouse-type thing to initially give packages, then a truck to give updates. That does have the drawback of ignoring existing metaphors, but perhaps it's fine in this case to differentiate between a status and an app

**Comment by danirabbit** [comment]
@wpkelso I wouldn't worry too hard about `system-software-update` since I think these days in most desktop environments updates aren't a separate app. This is probably something that could be proposed for deprecation in the naming spec imo

**Comment by wpkelso** [comment]
Closed by #1284
