### ISSUE TITLE
GNOME Builder misses info-symbolic icon

### ISSUE THREAD

**Issue by tintou** [elementary/icons#1184]
The project configuration pane features the `info-symbolic` icon that is not provided by our icon set

**Comment by Exalm** [comment]
It's actually not in adwaita-icon-theme either, and not in Builder. I.e. it seems it works by accident atm.

```
alexm@lenovo-thinkpad-x1-yoga /u/s/icons> sudo dnf provides /usr/share/icons/hicolor/scalable/status/info-symbolic.svg
[sudo] password for alexm: 
Last metadata expiration check: 3:03:20 ago on Sat 18 Mar 2023 19:28:44 +04.
gnome-control-center-43.1-1.fc37.x86_64 : Utilities to configure the GNOME desktop
Repo        : fedora
Matched from:
Filename    : /usr/share/icons/hicolor/scalable/status/info-symbolic.svg
```

So gnome-control-center installs the icon into the global theme. So yeah, this is an upstream bug.

**Comment by tintou** [comment]
Reported upstream https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/2015
