### ISSUE TITLE
Consider adding Inherits=hicolor to the index.theme file

### ISSUE THREAD

**Issue by milouse** [elementary/icons#1236]
### What Happened?

When using elementary icons theme, some application (like fuzzel) are not able to "fallback" on something when an icon is missing from the theme. On the other hand, a lot of third party application install their icon in the hicolor theme in order for them to be available.

I’m don’t know if this is a deliberate choice or not? And whether this is an error of the theme or if all applications are expected to do the fallback by themselves?

Adwaita theme for exemple does include this fallback.

If you confirm this is not a choice, I’m willing to post the fixing MR if you wish.

### Steps to Reproduce

```
fuzzel --icon-theme elementary
```

![capture_without](https://github.com/elementary/icons/assets/349239/bc7444b9-5017-4da6-b357-d815cad024de)

### Expected Behavior

![capture_with](https://github.com/elementary/icons/assets/349239/344a0c92-3d4f-4127-a7b6-97114168ecf3)

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

**Comment by newhoa** [comment]
I think this might actually be an issue with the app, not the icon theme.

According to the [FD.o Icon Theme Spec](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html):

> Implementations are required to look in the "hicolor" theme if an icon was not found in the current theme. 

And in the Standard Keys section (Table 1), `Inherits` is not a required key (and hicolor should be checked whether the `Inherits` line exists or not), noting:

> If no theme is specified implementations are required to add the "hicolor" theme to the inheritance tree.

So it seems fuzzel should add hicolor to their [icon lookup](https://codeberg.org/dnkl/fuzzel/src/commit/926e9362b1bf216be22552c7b57ef62f6daba534/icon.c#L206) as a final fallback, even if it's not in the `Inherits` line.
