### ISSUE TITLE
Only support the GTK/CSS cursor names

### ISSUE THREAD

**Issue by tintou** [elementary/icons#1255]
As per https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/74e9b79471236320d2af4925d6c5bb7df22380ce we should only ship the GTK/CSS cursors as Mutter will only use them

**Comment by danirabbit** [comment]
This would be much cleaner for sure. Glad for this change. Here's the list of supported cursors from the link:

https://docs.gtk.org/gdk4/ctor.Cursor.new_from_name.html

It should match the CSS spec:

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
