### ISSUE TITLE
Audio volume overamplified

### ISSUE THREAD

**Issue by peteruithoven** [elementary/icons#1265]
### Problem

[Clapper](https://github.com/Rafostar/clapper) one really great video player uses the icon `audio-volume-overamplified-symbolic` which is missing in elementary icons.
([Confirmed by developer here](https://github.com/Rafostar/clapper/discussions/427))

### Proposal

An overamplified icon is added

### Prior Art (Optional)

I think the following is the Adwaita icon?
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/master/Adwaita/symbolic/status/audio-volume-overamplified-symbolic.svg

I couldn't find a lot of alternatives
- https://iconduck.com/icons/160692/audio-volume-overamplified-symbolic
- https://iconduck.com/icons/164595/audio-volume-overamplified-symbolic
- https://icones.js.org/collection/all?s=overamplified (none found)
- https://thenounproject.com/search/icons/?q=overamplified (none found)

**Comment by tintou** [comment]
if it is not in the Freedesktop icon set, they should embed the icon in the application directly for fallback

**Comment by tintou** [comment]
See https://developer.gnome.org/documentation/tutorials/themed-icons.html#resources for how to do it

**Comment by peteruithoven** [comment]
That seems fair, thanks for the info @tintou, I've opened a new issue at Clapper to propose adding fallbacks.

**Comment by danirabbit** [comment]
Closing as "Out of Scope". Since this is not a freedesktop.org icon name it needs to be supplied by the app itself
