### ISSUE TITLE
Power profile (speed) icons

### ISSUE THREAD

**Issue by peteruithoven** [elementary/icons#1266]
### Problem

[Clapper](https://github.com/Rafostar/clapper) one really great video player uses the following icons to indicate speed which are missing in elementary icons:
- `power-profile-power-saver-symbolic`
- `power-profile-balanced-symbolic`
- `power-profile-performance-symbolic`

([Confirmed by developer here](https://github.com/Rafostar/clapper/discussions/427))

### Proposal

These power profile icons are added

### Prior Art (Optional)

Relevant Adwaita icons:
- https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/master/Adwaita/symbolic/status/power-profile-power-saver-symbolic.svg
- https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/master/Adwaita/symbolic/status/power-profile-balanced-symbolic.svg
- https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/master/Adwaita/symbolic/status/power-profile-performance-symbolic.svg

**Comment by danirabbit** [comment]
Same issue as the other one. Icons that aren't covered by the fd.o spec need to be gresourced by the developer

Closing as "out of scope"
