### ISSUE TITLE
update go-jump

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#13]
- [ ] Missing 32px
- [ ] Missing 64px
- [ ] Missing 128px
- [x] Uses old Tango-ish dark blue.
- [x] Missing 16px
- [x] Missing 48px -rtl
##

**Comment by snwh** [comment]
Others still missing.

**Comment by lainsce** [comment]
An update on this, noting what needs to be done:
- [ ] Still uses Tango-ish colors
- [ ] 64px missing
- [ ] 128px missing
