### ISSUE TITLE
Status: `user-`* icon styles differ between fullcolor and symbolic

### ISSUE THREAD

**Issue by newhoa** [elementary/icons#1307]
### What Happened?

The `user-` prefixed status icon for the fullcolor icons are colored dots. For symbolic, they are speech bubbles.

### Steps to Reproduce

Fullcolor:
![user-offline](https://github.com/user-attachments/assets/42a26146-7ccb-471f-8f3e-ba63317c73da)

Symbolic:
![user-offline-symbolic](https://github.com/user-attachments/assets/1c3441de-5071-4950-95a1-e939802bdb91)

### Expected Behavior

Ideally they should be the same. The [FD.o naming spec](https://specifications.freedesktop.org/icon-naming-spec/latest/) says these are specifically chat icons for the status of the user in chat. But it doesn't say what design should be used.

elementary seems to use the `user-` icons as device/network/general status icons (though Icon Browser lists them as chat icons). `user-away`, [for example](https://github.com/search?q=org%3Aelementary+user-away&type=code), is used for low ink in printer, when a document modified in Code, bluetooth is pairing, or network needs authentication. `user-offline` and `user-available`, [for example](https://github.com/search?q=org%3Aelementary+user-available&type=code), are used more as networking icons (where maybe `network-offline` would be more appropriate, but the FD.o dictates a style for that one which would not fit, and also there is no `network-available` name in FD.o).

So I don't really know which direction to go to make these uniform.

This shows some limitations in the FD.o spec which maybe could be updated to help resolve this sort of thing.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
See also https://github.com/elementary/icons/issues/827
