### ISSUE TITLE
Add Travis test for optimizing SVG files

### ISSUE THREAD

**Issue by codygarver** [elementary/icons#132]
There should be a test for optimizing all the SVGs, maybe it would run [svgo](https://www.npmjs.com/package/svgo).

**Comment by snwh** [comment]
I wouldn't be too heavy-handed with svgo, sometimes making icons virtually un-editable –the SVG syntax is fine, but it's visually messed up– if one isn't careful.

**Comment by cassidyjames** [comment]
How I've seen this done is by revision-controlling a "source" folder and then optimizing into an "optimized" folder. That way you never destroy your editable files, but it does mean more complex packaging and more files in the repo.

**Comment by danrabbit** [comment]
I'm going to close this since we've seen some really negative results with trying to process SVGs on the web repo
