### ISSUE TITLE
Grab cursor not appearing

### ISSUE THREAD

**Issue by teamcons** [elementary/icons#1326]
### What Happened?

Grabbing windows, icons, tabs, text do not bring up any grab cursor

### Steps to Reproduce

move icons in the dock
move windows
move windows in overview
move tabs in firefox
drag selected text

### Expected Behavior

the people are restless and they want grab cursor

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
I can reproduce the window drag cursor issue even with Icons 7.3.1. It looks like this is an upstream bug https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3624

It was fixed recently but we probably won't get that bugfix in Ubuntu LTS
