### ISSUE TITLE
HTML Pages for preview?

### ISSUE THREAD

**Issue by aadrian** [elementary/icons#134]
Add HTML Page(s) to preview all icons at once.

**Comment by snwh** [comment]
Nice thought, but their inclusion doesn't fit with the purpose of this repository or this theme.

**Comment by aadrian** [comment]
> Nice thought, but their inclusion doesn't fit with the purpose of this repository or this theme.

Not sure that I understand what you mean by that. 
Only when they're put together in a grid is visible if they're uniform and form a consistent theme.

**Comment by snwh** [comment]
Okay, there's no need to write an HTML page for previewing all icons at once. There is an app for that.
