### ISSUE TITLE
Come up with a generic name for the Ubiquity icon

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#137]
For use with the new pantheon installer or other OS installers that want to use this generic icon

**Comment by cassidyjames** [comment]
`system-installer`? That way it'd fall back on the computer-y icon but still have a prefix for `system-installer-install` or any other action icons specific to the installer.

**Comment by danrabbit** [comment]
Yeah I agree with `system` prefix. I think the convention upstream is to use `install` rather than `installer`, as in `system-software-install`. Maybe `system-os-install` ? Then we could have `system-os-update`, `system-os-reinstall` etc

**Comment by cassidyjames** [comment]
That's actually what @isantop and I were discussing a few mins ago. Makes
sense to me!
