### ISSUE TITLE
Add -secure icons for wired and cellular networks

### ISSUE THREAD

**Issue by png2378** [elementary/icons#147]
We have -secure icons for Wi-Fi, but we don't have them for wired and cellular networks. This leads to problems when using latest revisions of wingpanel-Indicator-network. 

Quote from [related](https://bugs.launchpad.net/wingpanel-indicator-network/+bug/1608005) bug report on Launchpad:

> We don't appear to have -secure icons for wired, we would also need -secure for all the cellular networks which makes me think
>
>We could have just the small lock as it's own icon, and use that on an overlay

**Comment by danrabbit** [comment]
Unfortunately we can't use an overlay because there's no way to mask around the vpn icon which would mean the icon would be hard to read.
