### ISSUE TITLE
Add icons for audio testing [$50]

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#158]
We need to replace this set of icons: https://github.com/GNOME/gnome-control-center/tree/8cfa46bddfbdb3238910d49ee0dd017fc6429df1/panels/sound/data/icons/scalable/devices

![screenshot from 2016-12-23 13 17 58](https://cloud.githubusercontent.com/assets/7277719/21462550/43c4eabc-c912-11e6-8c2b-6c0a4d8e5cf3.png)

- [ ] audio-speaker-center-back-testing.svg
- [ ] audio-speaker-center-back.svg
- [ ] audio-speaker-center-testing.svg
- [ ] audio-speaker-center.svg
- [ ] audio-speaker-left-back-testing.svg
- [ ] audio-speaker-left-back.svg
- [ ] audio-speaker-left-side-testing.svg
- [ ] audio-speaker-left-side.svg
- [ ] audio-speaker-left-testing.svg
- [ ] audio-speaker-left.svg
- [ ] audio-speaker-right-back-testing.svg	
- [ ] audio-speaker-right-back.svg
- [ ] audio-speaker-right-side-testing.svg
- [ ] audio-speaker-right-side.svg
- [ ] audio-speaker-right-testing.svg
- [ ] audio-speaker-right.svg
- [ ] audio-speaker-testing.svg
- [ ] audio-subwoofer-testing.svg
- [ ] audio-subwoofer.svg

---

https://www.bountysource.com/issues/40359618-add-icons-for-audio-testing

**Comment by Frenzy-Alex** [comment]
Hello, what size of icons is needed?
