### ISSUE TITLE
Use Cassidy's slashy lock

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#174]
The current `channel-insecure-symbolic` and `security-low-symbolic` icons are hard to distinguish from their secure counterparts. Cassidy mockup up a nice slashy lock that is much more clear.

![1-tyedjk26oo5zksxxwztbiq](https://cloud.githubusercontent.com/assets/7277719/23138442/5abc1308-f75c-11e6-8c54-971594b3a4fe.png)

**Comment by tintou** [comment]
It's wrong here, the lock has nothing to do with "security" but with "password protected", maybe the lock is wrong then
