### ISSUE TITLE
Create a "license" symbolic icon [$50]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#191]
For the app info view in AppCenter. Something like the ["balance-scale" icon in FontAwesome](http://fontawesome.io/icon/balance-scale/).

**Comment by danrabbit** [comment]
Making a note here that we could also use this for a`text-x-copying` mime

**Comment by danrabbit** [comment]
https://www.bountysource.com/issues/43184509-create-a-license-symbolic-icon

**Comment by vikaskyadav** [comment]
Check it out guyz. Anything like this?

![big-license](https://user-images.githubusercontent.com/12607959/27023830-daafe3e2-4f71-11e7-9fe6-3b7502d83a82.png)

![copyright](https://user-images.githubusercontent.com/12607959/27023856-f941ab42-4f71-11e7-8814-8628b175f2c5.png)
