### ISSUE TITLE
Create lesser generic icon for "Noise"

### ISSUE THREAD

**Issue by acagastya** [elementary/icons#198]
Current icon is a common and simple one. The design should be unique.

**Comment by danrabbit** [comment]
Gonna close as "won't fix". The purpose of this icon is to be legible not to be unique

**Comment by acagastya** [comment]
The icon can be legible, unique, and beautiful at the same time. So, why to say it won't fix? I want to contribute to the icon library, and I can try.

**Comment by danrabbit** [comment]
If you have a proposal, feel free to make a PR :)
