### ISSUE TITLE
Support EDS categories

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#2]
If I understand correctly, EDS has support for categories (and their icons) already.

We should support that and show the category icon in the sidebar and view and allow the category to be set in the event editing and creation dialog

> **Daniel Fore (danrabbit)**:
> It looks like EDS doesn't get or install the icons to the regular icon theme. I'm not sure there's a convention for this already. But we could just make our own -symbolic icons in the "categories" folder with the prefix "event".
> 
> So we'd want to create some icons like "event-birthday-symbolic" and "event-holiday-symbolic" etc

---

Originally filed by [Daniel Fore](https://launchpad.net/~danrabbit) on [Launchpad](https://bugs.launchpad.net/elementaryicons/+bug/1406019).
##

**Comment by danrabbit** [comment]
Marking as "Blocked" because we need to actually confirm this for Maya and decide on a set of icons to create

**Comment by danrabbit** [comment]
I'm going to close this since we created several category icons for Calendar already. New icons should be new reports
