### ISSUE TITLE
Have elementaryPlus like icons for all apps

### ISSUE THREAD

**Issue by uncertainquark** [elementary/icons#221]
[elementaryPlus](https://github.com/mank319/elementaryPlus) is an extended icon set to the default elementary icon set which make non-elementary apps look and feel like elementary icons. elementaryPlus also gives monochrome icons for all 3rd party idicators for apps. Like these:

![](https://github.com/mank319/elementaryPlus/raw/master/AppIconPreview.png)
![](https://github.com/mank319/elementaryPlus/raw/master/StatusIconPreview.png)

It brings so much cohesiveness to the entire system. It would be nice to have elementaryPlus adopted in the default elementary icon set or to have similar icons added for all 3rd party apps if possible.

**Comment by danrabbit** [comment]
This is covered in the [Readme](https://github.com/elementary/icons/blob/master/README.md). Marking as "won't fix"

**Comment by uncertainquark** [comment]
Okay the fact that those icons are not universal and thus can't be integrated makes sense. But can new icons be created in line with the FreeDesktop specifications in mind? Because as things stand right now, non elementary app icons do look out of place.

**Comment by snwh** [comment]
The specification is a standardized set of icons across the linux desktop, third party application icons aren't a part of the spec and we have a policy of not changing the branding of third parties. The elementary set has been designed to fit the Tango specification for icons, if Linux apps choose not to make Tango icons that's their choice.
