### ISSUE TITLE
The mail-sent icon is a different icon at bigger size. 

### ISSUE THREAD

**Issue by matzipan** [elementary/icons#226]
![screenshot from 2017-06-12 00 36 59](https://user-images.githubusercontent.com/317239/27015540-9a06c28a-4f07-11e7-82d2-39332f38cf73.png)
![screenshot from 2017-06-12 00 37 33](https://user-images.githubusercontent.com/317239/27015539-9a055d78-4f07-11e7-9445-04444144e33b.png)

Attached are previews of the icons at BUTTON size (I believe 24px) and LARGE_TOOLBAR size (I believe 32px).

There's a another icon, document-send, which has significant overlap with this icon.

**Comment by danrabbit** [comment]
This is 16px and 24px, respectively. I can confirm the issue.

Please note that "document-send" is an action icon and "mail-sent" is a places icon.

It looks like we don't currently supply a "document-send" icon. You might want to open another issue report about symlinking "document-send" to "mail-send" or vice versa.
