### ISSUE TITLE
Symlink "document-send" to "mail-send" or the other way around

### ISSUE THREAD

**Issue by matzipan** [elementary/icons#229]
This was raised as an idea in #226.

**Comment by danrabbit** [comment]
I just noticed we actually have a symbolic icon for document-send which is the paper with an up arrow. So maybe we've previously decided to differentiate these purposefully

**Comment by danrabbit** [comment]
Closing because this seems to be different semantically and I have a proposal for an icon open

**Comment by waldyrious** [comment]
> I have a proposal for an icon open

#536
