### ISSUE TITLE
Improve microphone icons

### ISSUE THREAD

**Issue by snwh** [elementary/icons#238]
These are some of the oldest in the set, could use a new design.

**Comment by danrabbit** [comment]
I'd really like it if we could try to make the color and symbolic icon sets match each other more closely. So maybe a mic in this sort of style:

![mic](https://cdn.dribbble.com/users/550484/screenshots/3383232/music-icons.png)

![mic](https://cdn.dribbble.com/users/550484/screenshots/3383232/music-icons.png)

**Comment by snwh** [comment]
I'm already ahead of ya :wink:

**Comment by danrabbit** [comment]
https://www.bountysource.com/issues/46227018-improve-microphone-icons

**Comment by vikaskyadav** [comment]
hii,
Check if any of these fits our requirements.

![microphone](https://user-images.githubusercontent.com/12607959/27195514-ba0e6ba8-5224-11e7-88d6-295ff5e6d5d0.png)

![microphone 1](https://user-images.githubusercontent.com/12607959/27195517-bfc1ec50-5224-11e7-93e5-2ebcd05b66ca.png)

![microphone 2](https://user-images.githubusercontent.com/12607959/27195559-e37cdf60-5224-11e7-8a02-e3a4f2bd5a0e.png)
