### ISSUE TITLE
Aging symbolic icons

### ISSUE THREAD

**Issue by snwh** [elementary/icons#259]
Many of our 16x16 pixel symbolic icons have a lot of inconsistencies and there is a general lack of consistency throughout the set. Also many icons that we inherited from GNOME are still in place.

**Comment by J0Ar** [comment]
Will this change also solve some missing icons in 'non-elementary-apps'? 

I'm asking bcause i'm using **audacious** (music player) and i found out the only way to get a consistence look is to install the _xubuntu-icon-theme_ and make a ''Inherits=elementary-xfce-darker'' in ''/usr/share/icons/elementary/index.theme''

only with 'elementary-icon-theme' the _volume_ and _shuffle?_ icons are from gnome (or adwaita?):
![elementary_icons](https://user-images.githubusercontent.com/23266409/28498394-ada37a58-6f9c-11e7-9c51-92495d757991.png)
with 'elementary-icon-theme' and 'Inherits=elementary-xfce-darker'-edit everything is ok:
![elementary_inherits_xubuntu_icons](https://user-images.githubusercontent.com/23266409/28498400-ec803608-6f9c-11e7-8885-d5781abf87c6.png)

Thanks for your work :)

**Comment by snwh** [comment]
This issue is for the symbolic icon set which are used in the panel for example.

**Comment by snwh** [comment]
Gonna say this is fixed
