### ISSUE TITLE
Can I change the window action buttons? (close, minimize, maximize)

### ISSUE THREAD

**Issue by TopherHamn** [elementary/icons#325]
I want to change the icons for better ones

**Comment by danrabbit** [comment]
This is not a support forum. Please see [StackExchange](https://elementaryos.stackexchange.com/) instead

**Comment by alejandro6901** [comment]
I don't like those icons, is a good idea to change them!

**Comment by snwh** [comment]
By all means, you can change the icons in your local set–you can find them in the theme directort in `actions/symbolic/window-*-symbolic.svg` and can swap them out for whichever icons you prefer–but we won't be changing them in the main theme. However, I'll look at any pull request for an icon change you think is "better".
