### ISSUE TITLE
Missing 24px network-cellular icons

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/icons#340]
Currently working on adding support for cellular modems in the indicator and switchboard. Noticed that a couple of the 24px symbolic icons for the network-cellular-* set are missing, causing them to look the wrong size in wingpanel.

![image](https://user-images.githubusercontent.com/3372394/30507005-6ef7daea-9a78-11e7-8f9d-e32238336d04.png)

**Comment by danrabbit** [comment]
I can confirm the following are missing:
- [ ] network-cellular-acquiring-symbolic
- [ ] network-cellular-connected-symbolic
- [ ] network-cellular-no-route-symbolic
- [ ] network-cellular-offline-symbolic

Also all signal strengths with `-secure`
