### ISSUE TITLE
24px network-cellular icons too low on canvas

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/icons#351]
I believe this is the cause of the alignment issue demonstrated in the screenshot below, many of the other panel icons start at least 1px higher. I feel as though it might benefit from being slightly taller too.

Happy to help with getting screenshots and testing etc...

![screenshot from 2017-09-25 00 22 52](https://user-images.githubusercontent.com/3372394/30787751-fc922b06-a187-11e7-9c01-e0246d549566.png)

**Comment by snwh** [comment]
Fixed in #360
