### ISSUE TITLE
deb package icon

### ISSUE THREAD

**Issue by AlonsoEnrique** [elementary/icons#358]
rpm also is missing

**Comment by snwh** [comment]
They're using the package icons, seems alright to me.

**Comment by AlonsoEnrique** [comment]
hi @snwh, but there is no difference between .zip, .deb or .rpm and so.
![packages](https://user-images.githubusercontent.com/1877511/32076473-b091d58e-ba65-11e7-9ca1-1c3b1e511f22.png)

**Comment by AlonsoEnrique** [comment]
Example icons: http://devblog.info/wp-content/uploads/2016/08/deb-icon.png or http://downloadicons.net/sites/default/files/deb-icon-13164.png

**Comment by MrMarukesu** [comment]
in fact, this is a bug, .deb mimetype is not loading the application-x-deb icon and loads the package-x-generic instead

**Comment by MrMarukesu** [comment]
renaming the icon to application-vnd.debian.binary-package fix this here
![screenshot from 2018-02-17 23-47-55](https://user-images.githubusercontent.com/21296444/36347388-37e1f98e-143d-11e8-997a-10bec4bc552e.png)
