### ISSUE TITLE
Laptop device icons

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#383]
@danrabbit mentioned that it'd be dope to have a laptop device icon, similar to the video-display icons we have now. Then we could do more interesting things, for example in the About plug with laptop-detect.

**Comment by TraumaD** [comment]
Interested

**Comment by TraumaD** [comment]
![device-laptop](https://user-images.githubusercontent.com/10608836/34859718-a6df72e0-f71d-11e7-8481-56da962d1ce9.png)
Thoughts?

**Comment by TraumaD** [comment]
or
![device-laptop64](https://user-images.githubusercontent.com/10608836/34862740-8789d746-f731-11e7-88fb-c127e3565ed6.png)

**Comment by danrabbit** [comment]
Oh man that latest one looks really dope.

I think I would go with `computer-notebook` because it would fall back cleanly to `computer`

**Comment by TraumaD** [comment]
![computer-notebook_128](https://user-images.githubusercontent.com/10608836/34883197-8504d032-f77e-11e7-8ec7-6e1f14fe608e.png) ![computer-notebook_64](https://user-images.githubusercontent.com/10608836/34883141-5ad4490a-f77e-11e7-8643-b5db783d8463.png)

Progress:
- [x] 128px
- [x] 64px
- [ ] 48px
- [ ] 32px
- [ ] 24px
- [ ] 16px

**Comment by cassidyjames** [comment]
Posted over at https://github.com/cassidyjames/dippi/issues/29 as well, but copying here so others can follow.

>I really love the perspective and display on that. If I'm being picky, I might say that it still looks a little chunky at the bottom. I think if it could look a little more idealized razor-thin it would be rad. but that's a nit.
>
>Color-wise I really like the black but I think the two-tone inside/outside is a little specific to the Dell XPS 13. I think either all black or a silver chassis might be more common/generic. But a black bezel. :ok_hand:
>
>Last nit: the glare on the display might be a little harsh, but I think just whatever is consistent with the elementary style is fair game here. It's hard to know out of context.

Even without any changes, I'm pretty happy with these. They look super hot. Nice work, @TraumaD!

**Comment by TraumaD** [comment]
![computer-notebook_128_2](https://user-images.githubusercontent.com/10608836/34889688-8a708a78-f794-11e7-8749-95b866635b5e.png)
@cassidyjames more like this?

**Comment by cassidyjames** [comment]
Nice! Digging the thinness and display. I'm torn between all-black versus silver. @danrabbit, thoughts?

**Comment by cassidyjames** [comment]
Alrighty, I think I do like the silver one better. It's more distinctly a laptop. Nice work. :)

**Comment by danrabbit** [comment]
Yeah I would go for the higher contrast option. Looks ace dude

**Comment by snwh** [comment]
These are nice, silver is definitely the way to go

**Comment by TraumaD** [comment]
I think that's it unless you all have anymore suggestions. Should I go ahead and send a PR?
