### ISSUE TITLE
devices/input-tablet missing at all sizes [$50]

### ISSUE THREAD

**Issue by snwh** [elementary/icons#40]
- [x] 16px
- [x] 24px
- [x] 32px
- [x] 48px
- [x] 64px
- [x] 128px

--
[Bounty Link](https://www.bountysource.com/issues/29252788-devices-input-tablet-missing-at-all-sizes)

**Comment by Ghokun** [comment]
![input-tablet](https://cloud.githubusercontent.com/assets/3802058/15243212/ef956454-1902-11e6-8118-076126f6e943.png)

SVG of this icon is wanted, right?

**Comment by snwh** [comment]
That's the GNOME icon. The bug is to add an input-tablet elementary icon to the theme, which I'm already working on. ;)
