### ISSUE TITLE
Symbolic tag icon

### ISSUE THREAD

**Issue by artemanufrij** [elementary/icons#403]
can we got a `tag `and `tag-symbolic` icon? currently are only `tag-new` and `tag-new-symbolic` exist.

**Comment by danrabbit** [comment]
`tag` exists in 16px (it's in `places`), but it looks like `tag-symbolic` is missing.

**Comment by artemanufrij** [comment]
hey @danrabbit, I can't push a PR without clone whole project (permission denied).
here is symbolic icon:
[tag-symbolic.svg.zip](https://github.com/elementary/icons/files/1665030/tag-symbolic.svg.zip)
