### ISSUE TITLE
Make 'open-menu' and 'document-properties' icons different

### ISSUE THREAD

**Issue by rkoesters** [elementary/icons#406]
Currently, the 'open-menu' and 'document-properties' icons are identical. However some applications make use of both icons in their user interface. Take a look at evince (elementary's default PDF viewer), its headerbar has a menu using 'document-properties' right next to a menu using 'open-menu' (actually it uses the symbolic version of each icon). This looks sloppy and confusing.

![image](https://user-images.githubusercontent.com/1441440/35453860-4dc608ca-0291-11e8-8990-6f231238e1da.png)

We could fix this by patching evince to not do that, but there are potentially apps that do the same that I am not aware of, so making the icons different may be the way forward.

**Comment by TraumaD** [comment]
We could start using `view-more-symbolic` vertical ellipsis glyph for `open-menu` instead of the gear glyph as mentioned in #380.
