### ISSUE TITLE
security-foo icons are all the same

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#410]
We should come up with some way to distinguish between `security-low`, `security-medium`, and `security-high`. Right now it's just symlinked to the lock icon. It looks like other icon sets are using a shield metaphor.

One thing we could do is use color and have a yellow shield for low, grey for medium, green for high

**Comment by TraumaD** [comment]
Thoughts?
![security](https://user-images.githubusercontent.com/10608836/35473749-2eff3d62-034a-11e8-9ced-576f653814d1.png)

**Comment by danrabbit** [comment]
![colors](https://user-images.githubusercontent.com/7277719/35477871-a88a34ec-0382-11e8-9b55-dd098534c420.png)

Trying to reproduce your shape a bit here... What do you think of doing something like this, maintaining a more polished steel looking border?
