### ISSUE TITLE
"Mystery man" shape is inconsistent

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#413]
The shape of the "mystery man" differs between icons that use this concept like:

actions:
`address-book-new`
`contact-new`

![contact-new](https://user-images.githubusercontent.com/7277719/37257933-0008c7c6-252d-11e8-8afc-4bcec0b11f7e.png)

apps:
`office-address-book`
`system-users`

![office-address-book](https://user-images.githubusercontent.com/7277719/37257931-fb37fc4e-252c-11e8-94d2-48083e882014.png)

![screenshot from 2018-03-11 13 04 39 2x](https://user-images.githubusercontent.com/7277719/37257928-f571b58e-252c-11e8-83b8-1eccb7b77cca.png)

mimes:
`office-contact`

![vcard](https://user-images.githubusercontent.com/7277719/37257956-84f939a2-252d-11e8-82e6-513358f53235.png)

status:
`avatar-default`

![screenshot from 2018-03-11 13 05 00 2x](https://user-images.githubusercontent.com/7277719/37257925-ef21cc6e-252c-11e8-91b2-95817637326b.png)

**Comment by cassidyjames** [comment]
I definitely like the less-masculine and more symbolic `avatar-default` person. The general shape and little hair tuft on the contact and address icons feels super masculine. `system-users` looks pretty… alien or something. :D

**Comment by cassidyjames** [comment]
Twitter had some interesting findings when working through their new default avatar, though I think its overall shape feels too egg-y for us. Still good reading, though. https://blog.twitter.com/en_us/topics/product/2017/rethinking-our-default-profile-photo.html

**Comment by danrabbit** [comment]
Yeah I agree that doing something more gender-neutral would be more ideal

**Comment by waldyrious** [comment]
There are some vector images in [Wikimedia Commons](https://commons.wikimedia.org/wiki/Category:SVG_blank_persons_placeholders), in case that helps with additional design inspiration.

**Comment by SixFingeredAmish** [comment]
Facebook designers' discussion on this topic might be useful here. https://medium.com/facebook-design/how-we-changed-the-facebook-friends-icon-dc8526ea9ea8
