### ISSUE TITLE
Install the palette

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#424]
It would be convenient if this package would just install the palette file so that it was present out of the box

**Comment by TraumaD** [comment]
Are we auto installing for inkscape and GIMP or just somewhere on the system so as to easily be imported into whatever program you're using?

**Comment by danrabbit** [comment]
I think we should auto install for Inkscape and GIMP. It should be okay to create those config directories even if those apps aren’t installed, I think

**Comment by TraumaD** [comment]
Yeah, I think you are right. I believe they can go to `/usr/share/inkscape/palettes` and `/usr/share/gimp/2.0/palettes`.

**Comment by codygarver** [comment]
Closed via #436
