### ISSUE TITLE
There is no icon-theme.cache for elementary icons on elementary OS

### ISSUE THREAD

**Issue by Shnatsel** [elementary/icons#433]
If you navigate to /usr/share/icons/gnome on Loki, you'll see a file called `icon-theme.cache` in that folder. However, there is no such file in /usr/share/icons/elementary folder. 

We're probably missing out on some icon lookup optimizations that would be especially noticeable on HDDs. There is a very good explanation of what this cache does on AskUbuntu: https://askubuntu.com/a/279794/4770

**Comment by Shnatsel** [comment]
If you delete icon-theme.cache in /usr/share/icons/gnome and run `sudo apt-get install --reinstall gnome-icon-theme` that file will be regenerated. Also, `gnome-icon-theme` package ships an apt trigger that regenerates the cache every time something is installed or removed under /usr/share/icons/gnome, see debian/triggers and debian/postinst in `gnome-icon-theme` package source code.

**Comment by Shnatsel** [comment]
I've armed myself with [statsnoop](https://github.com/iovisor/bcc/blob/master/tools/statsnoop_example.txt) and confirmed that enabling icon theme cache shaves off 1,000 `stat()` syscalls on wingpanel startup. This should also apply to any other GUI application that uses elementary icons.

**Comment by tintou** [comment]
@Shnatsel prepare your PR ;) https://github.com/elementary/icons/tree/deb-packaging

**Comment by danrabbit** [comment]
Seems like this was fixed in the referenced PR above
