### ISSUE TITLE
"notification-disabled" and "notification-disabled-symbolic" are inconsistent

### ISSUE THREAD

**Issue by fabiozaramella** [elementary/icons#446]
See attached screenshots.

![schermata del 2018-03-11 20 22 12](https://user-images.githubusercontent.com/5459945/37257526-e3d8c0f4-256a-11e8-87b9-f4ba34879699.png)

![schermata del 2018-03-11 20 22 32](https://user-images.githubusercontent.com/5459945/37257529-eb1d592e-256a-11e8-9405-2ddaa212c0eb.png)

**Comment by Djaler** [comment]
I suggest to mark this as a critical :D
