### ISSUE TITLE
Some mimetypes are missing in 16px and 24px

### ISSUE THREAD

**Issue by tintou** [elementary/icons#453]
A screenshot is better than thousands words: happening in Code
![capture d ecran du 2018-03-14 10 29 50 2x](https://user-images.githubusercontent.com/745535/37397225-ed1facd6-2772-11e8-801c-ff363bb818eb.png)

specifically this shows:
- [ ] text-x-chdr
- [ ] text-x-csrc
- [ ] text-html

**Comment by micahilbery** [comment]
Does this not also show text-x-python?
