### ISSUE TITLE
Same icon has multiple meanings

### ISSUE THREAD

**Issue by SolarLiner** [elementary/icons#472]
In the PDF viewer, two header bar buttons show a gear icon (image 1). Now I agree the use of two different menus is maybe a it misleading, but using the Papirus icon theme we can see that two different images (image 2).

![capture d ecran du 2018-04-09 22 49 57](https://user-images.githubusercontent.com/4302963/38524274-59120d18-3c4e-11e8-83ba-52aaceb95014.png)
![capture d ecran du 2018-04-09 23 31 16](https://user-images.githubusercontent.com/4302963/38524273-58f3c4ca-3c4e-11e8-8f8e-9a8bacd548ef.png)

I suggest tweaking one of the icons on the theme to imply a different meaning.

**Comment by micahilbery** [comment]
Duplicate of #406?

**Comment by SolarLiner** [comment]
Oh, right. Late-ish night time and light sickness don't go well together.

This is a duplicate of #406.
