### ISSUE TITLE
Redo palette purple

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#498]
It doesn't seem to match any of the icons. I'm not sure where it came from :p

**Comment by micahilbery** [comment]
Things I can think of that we'll probably want to fix after this:
[ ] Developer page
[ ] Appcenter icon
[ ] Appcenter redirect

**Comment by danrabbit** [comment]
- [ ] Get It On AppCenter badge

**Comment by danrabbit** [comment]
Re-opening because we're tracking some other stuff here

**Comment by danrabbit** [comment]
Closing since the only thing left is Houston and we can track that here: https://github.com/elementary/houston/pull/618
