### ISSUE TITLE
32px battery full and full-charged wrong 

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#507]
![screenshot from 2018-05-09 18 02 54 2x](https://user-images.githubusercontent.com/7277719/39846907-3f900a08-53b3-11e8-8561-5c99051131f9.png)

full-charged is missing and full should be blue

while we're here, full-charging should be blue also

**Comment by micahilbery** [comment]
Should we also make `battery-full-charged-symbolic` blue then?
