### ISSUE TITLE
[REQ] .so (application/x-sharedlib) mime icon

### ISSUE THREAD

**Issue by re23071998** [elementary/icons#525]
i have no idea how its should looks like, I think puzzle pieces suitable for this icon

**Comment by danirabbit** [comment]
This was fixed :)

**Comment by waldyrious** [comment]
> This was fixed :)

Adding a link to the relevant PR, for future reference: #1119 (It did mention #806, which in turn mentioned this issue, but it's more convenient to have the direct link.)
