### ISSUE TITLE
Move nm-device icons from status to devices

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#53]
Until these icons can be retired, probably should move them to the devices folder

- [ ] nm-device-wwan
- [ ] nm-device-wireless
- [ ] nm-device-wired
- [ ] nm-device-wired-secure

**Comment by snwh** [comment]
Does anything use nm-device-* ?

**Comment by danrabbit** [comment]
I believe that Ubiquity still uses nm-* icons
