### ISSUE TITLE
audio symbolic (duplicate) in wrong directory

### ISSUE THREAD

**Issue by NikoKrause** [elementary/icons#547]
There are `audio-x-generic-symbolic.svg` icons in `mimes/48` and `mimes/64`.

**Comment by danrabbit** [comment]
This isn’t a bug. These icons are intentionally hinted

**Comment by NikoKrause** [comment]
Why are they there? Just interested.

**Comment by danrabbit** [comment]
@NikoKrause they're used in the album view in Music at various sizes. Hinting ensures that they scale to fit the canvas properly and are pixel aligned at each size
