### ISSUE TITLE
BibTeX mime suggestion

### ISSUE THREAD

**Issue by NikoKrause** [elementary/icons#568]
I created a mime for BibTeX files. It's inspired by this icon https://opencontext.org/about/bibliography:
![screenshot-area-2018-05-16-215400](https://user-images.githubusercontent.com/8415124/40140611-aad96bf6-5953-11e8-93fc-44f2a273d129.png)

If you like it, I can create a PR:
![screenshot-area-2018-05-16-215426](https://user-images.githubusercontent.com/8415124/40140648-bb382816-5953-11e8-8973-948bdf0bf1da.png)

**Comment by danrabbit** [comment]
Metaphor looks fine to me, but it seems like the colors are a bit harsh and it seems very flat (no highlights, shadows, etc). I think our standard for text in mimetype right now is Silver 700. Might want to try with that color instead :(

**Comment by NikoKrause** [comment]
Ah yes. I use a flat version of elementary mimes. For the PR i will adapt the elementary style with shadows etc of course. I'll also change the color to Silver 700
