### ISSUE TITLE
Minor typo in Scanner icon

### ISSUE THREAD

**Issue by D0J0P** [elementary/icons#580]
Looking at the Scanner icon [here](https://github.com/elementary/icons/blob/master/devices/128/scanner.svg), and zooming in real close you can see a small typo in the second paragraph where it says "It should be beyond cutting **ede**".

**Comment by NikoKrause** [comment]
![screenshot-area-2018-05-17-193054](https://user-images.githubusercontent.com/8415124/40193922-102232f8-5a09-11e8-9ac7-64764f9360dc.png)

**Comment by NikoKrause** [comment]
Anybody noticed that you can sing this text to the Pokemon theme song?

**Comment by D0J0P** [comment]
Thanks for the picture. And yeah, the Pokemon theme was the first thing that popped into my head when I first read this lol!
