### ISSUE TITLE
Meson build not working

### ISSUE THREAD

**Issue by emansije** [elementary/icons#587]
I never managed to make the meson build work. I did an adaption to the instructions:

```bash
$ meson build --prefix=~/.local
$ cd build
$ meson install
```

... but it keeps throwing the following error:

```
Error during basic setup:

Neither directory contains a build file meson.build.
```

I'm on Ubuntu 18.04 using the meson available in the official repositories. Am I forgetting some step?

**Comment by NikoKrause** [comment]
```
ninja install
```
instead of
```
meson install
```

**Comment by tintou** [comment]
Yeah indeed a typo in the build instructions, fixed in master

**Comment by waldyrious** [comment]
> fixed in master

In particular, in commit 07c948a96.
