### ISSUE TITLE
Add Sass mime

### ISSUE THREAD

**Issue by stsdc** [elementary/icons#589]
Because it is really confusing right now 
![obraz](https://user-images.githubusercontent.com/6031763/40246378-d89c3912-5ac8-11e8-9c49-4a3a6782ee69.png)

**Comment by stsdc** [comment]
Made this, but I don't know how to properly name it. Some mimetype icon names start with _application_ others with _text_... :man_shrugging: 
![sass](https://user-images.githubusercontent.com/6031763/40581133-18361f28-6151-11e8-8aa6-12f04a2ca3e3.png)

**Comment by tintou** [comment]
just right click on your file to see the mime type
![capture d ecran du 2018-05-28 10 34 46 2x](https://user-images.githubusercontent.com/745535/40608247-c4ec291c-6262-11e8-90dd-8a4f6f57548d.png)
`text/x-sass` means that the icon should be named `text-x-sass`

**Comment by NikoKrause** [comment]
Looking at ![`shared-mime-info` on freedesktop.org](https://cgit.freedesktop.org/xdg/shared-mime-info/tree/freedesktop.org.xml.in#n6223) it lists two mime types for `Sass CSS pre-processor file`:
```
  <mime-type type="text/x-sass">
    <_comment>Sass CSS pre-processor file</_comment>
    <sub-class-of type="text/plain"/>
    <glob pattern="*.sass"/>
    <generic-icon name="text-x-generic"/>
  </mime-type>

  <mime-type type="text/x-scss">
    <_comment>Sass CSS pre-processor file</_comment>
    <sub-class-of type="text/plain"/>
    <glob pattern="*.scss"/>
    <generic-icon name="text-x-generic"/>
  </mime-type>
```

So name your icon `text-x-sass.svg` and add symbolic links `text-x-scss.svg`.

**Comment by NikoKrause** [comment]
https://sass-lang.com/styleguide/brand

**Comment by stsdc** [comment]
@tintou interesting that it shows me text/plain
![obraz](https://user-images.githubusercontent.com/6031763/40627441-57df0cce-62bf-11e8-9e06-dce668e72648.png)

**Comment by NikoKrause** [comment]
What's the content of the file?

**Comment by alainm23** [comment]
The same as css

**Comment by stsdc** [comment]
@NikoKrause 
![obraz](https://user-images.githubusercontent.com/6031763/40628114-58c4eb82-62c3-11e8-8a6e-925953253026.png)

**Comment by stsdc** [comment]
You're right!
