### ISSUE TITLE
Add Typescript mime

### ISSUE THREAD

**Issue by alainm23** [elementary/icons#590]
Currently there is a tendency to work with Angular and Ionic, I use it in my daily work and I would like to have some mime for this text format
![ts_mime](https://user-images.githubusercontent.com/33765137/40247419-e83da82e-5a91-11e8-9efe-14eaf542c2e4.png)

**Comment by stsdc** [comment]
Based on Typescript Twitter :man_shrugging: 
![ts](https://user-images.githubusercontent.com/6031763/40581395-841f3ba6-6157-11e8-9dd8-3be18d91d17c.png)

**Comment by stsdc** [comment]
What is the proper typescript mimetype name ?

**Comment by alainm23** [comment]
![captura realizada el 2018-05-30 09 00 40](https://user-images.githubusercontent.com/33765137/40725005-ffb2a55e-63e7-11e8-9fde-5a30b263378e.png)

**Comment by NikoKrause** [comment]
It might be `application/typescript` according to [Mozillas MIME type list]( https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types) as you say, but Ubuntu is getting it's mimetype info from [shared-mime-info (freedesktop)](https://cgit.freedesktop.org/xdg/shared-mime-info/tree/freedesktop.org.xml.in). It lists 2 mimetypes for `*.ts` file endings.
1. MPEG-2 transport stream (video files): type: `video/mp2t`
2. message catalog (text files); type: 
```
  <mime-type type="text/vnd.qt.linguist">
    <_comment>message catalog</_comment>
    <sub-class-of type="application/xml"/>
    <magic>
      <match type="string" value="&lt;TS" offset="0:256"/>
    </magic>
    <glob pattern="*.ts"/>
    <alias type="application/x-linguist"/>
    <alias type="text/vnd.trolltech.linguist"/>
  </mime-type>
```

It doesn't list anything for typescript at all. This means, if you are having a TypeScript file with `.ts` ending, it will be shown as `text/vnd.qt.linguist` or `text/vnd.trolltech.linguist` or `application/x-linguist` (I tested it on Ubuntu 18.04 with a typescript file and it shows `text/vnd.trolltech.linguist`).

The suggested icon from @stsdc ![TS](https://user-images.githubusercontent.com/6031763/40581395-841f3ba6-6157-11e8-9dd8-3be18d91d17c.png) seems pretty neutral to me, it shows the letters of the file ending `*.ts`. So I think it would be ok to use this no matter if it is a TypeScript file or if it is a Qt translation file.

**Comment by stsdc** [comment]
If it is not in freedesktop list, I'm not sure that I should add this mimetype now.

**Comment by NikoKrause** [comment]
There's no mimetype listed for typescript files, but there's listed a mimetype for `.ts` files called `text/vnd.trolltech.linguist`, which can be added. I suggest an icon, which looks like a paper with a `TS` or `.ts` (the letters for the file ending) on it as it is done for `.h` files: 
![screenshot-area-2018-05-31-230423](https://user-images.githubusercontent.com/8415124/40808302-01dbe832-6527-11e8-91ed-8f7b0353c3fa.png)

**Comment by btd1337** [comment]
@stsdc just refer the icon suggest above to mimetype text/vnd.trolltech.linguist. This will solve the problem untill _freedesktop_ to add the Typescript to your database.

**Comment by tintou** [comment]
No guys, we can't just do it like this, `text/vnd.trolltech.linguist` is for something else.

**Comment by btd1337** [comment]
@tintou What do you suggest?

**Comment by NikoKrause** [comment]
@scop Is it possible to get an own mimteype for typescript files in some future version of shared-mime-info? Any help is appreciated.

**Comment by scop** [comment]
shared-mime-info issues should be filed in the freedesktop.org bugzilla.

https://www.freedesktop.org/wiki/Software/shared-mime-info/
https://bugs.freedesktop.org/enter_bug.cgi?product=shared-mime-info

But better than reporting a shared-mime-info issue, the right thing to do for typescript is to submit it to the official IANA registry. From there it propagates to many places, including shared-mime-info. https://www.iana.org/assignments/media-types/

**Comment by danirabbit** [comment]
There's already an icon for typescript here, so this is a mime info bug. Closing since there's nothing we can do in icons, we'll already supplying a typescript icon
