### ISSUE TITLE
Unlock/unlocked icon

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#607]
In the installer, I'm wanting to be able to show the lock/unlocked status on drives. I noticed we don't have an unlock icon, though some other icon sets appear to.

This is distinct from both a password and a low security icon, as it's not requesting someone to enter a password, nor is it saying something is low security (it's just currently unlocked).

**Comment by danrabbit** [comment]
I think we should have symbolic versions of this icon since it’s used by Gtk lock button. Is this for a colored version?

**Comment by cassidyjames** [comment]
Ah, it's `changes-allow` and `changes-prevent` That took a lot of digging. :sweat_smile: Those work for me.
