### ISSUE TITLE
No icons for Code

### ISSUE THREAD

**Issue by ryonakano** [elementary/icons#621]
Related [#1969 of website](https://github.com/elementary/website/pull/1969) and [#1974 of website](https://github.com/elementary/website/pull/1974).
It seems that there is no icons for Code in this repo and only exist in the Code repo.

**Comment by danrabbit** [comment]
This is intentional and isn't a bug. Closing as "Out of scope" since it isn't the intention of this repo to ship non-generic app icons

**Comment by ryonakano** [comment]
https://github.com/ryonakano/website/blob/22b298cc1abf2689654d26305f0453ad5730cc42/index.php#L119
@danrabbit I understand the intention. I'm sorry if I am ignorant, however, I have a reason why I've posted this issue: the website uses `apps/64/accessories-text-editor.svg` which is in this repo, as the icon of Scratch. I think the icon will have to replace to Code's one since Scratch is renamed to Code. So I suppose we may want to add the Code icon to this repo.

**Comment by danrabbit** [comment]
@ryonakano It would be better to add the Code icon to the website ;)

**Comment by ryonakano** [comment]
@danrabbit Where do you think is better directory in the website? I guess it's any directory in the `_images` directory, but I have no idea which subdirectory is appropriate.

**Comment by danrabbit** [comment]
@ryonakano It would probably be better to ask this on your pull request or issue report for the website. This repo is not within the scope of that discussion

**Comment by ryonakano** [comment]
@danrabbit Well noted with thank you.
