### ISSUE TITLE
Mime Request - application/json

### ISSUE THREAD

**Issue by btd1337** [elementary/icons#623]
Please, add application/json mimetype icon

**Comment by NikoKrause** [comment]
Json has a logo: https://commons.wikimedia.org/wiki/File:JSON_vector_logo.svg

Not sure, if it can be used or if there are some issues as with the Java icon.

**Comment by btd1337** [comment]
I believe that the CSS icon used in this theme is more appropriate to JSON than it is itself.

![json](https://user-images.githubusercontent.com/11943860/42296280-559c07f0-7fca-11e8-9a50-4fccde0b86cb.png)

JSON is very attached to the brackets. 

CSS is more connected to your default symbol

![css](https://user-images.githubusercontent.com/11943860/42296302-9180ea06-7fca-11e8-9f01-5aeaccee3d0b.jpg)

You could consider studying this case.

**Comment by NikoKrause** [comment]
What do you think about this one (based on the JSON logo: https://commons.wikimedia.org/wiki/File:JSON_vector_logo.svg)

![grafik](https://user-images.githubusercontent.com/8415124/80186689-b3a7bc80-860e-11ea-8f81-3af9cb8e0c58.png)

**Comment by NikoKrause** [comment]
![image](https://user-images.githubusercontent.com/8415124/80209068-a6e89000-8631-11ea-829c-6778e7d3091a.png)

Or do you want to go in this direction. Let me know so I can prepare a PR
