### ISSUE TITLE
Missing icon for Geary "Detach" button

### ISSUE THREAD

**Issue by uncertainquark** [elementary/icons#624]
In Geary's mail composer, there is a detach button. It is missing an icon in Juno Beta-1 (shown by the cursor position in the screenshot).

![screenshot from 2018-07-08 22 10 39](https://user-images.githubusercontent.com/22585732/42422000-402dda1c-82fc-11e8-9382-a20088a78fc5.png)

**Comment by danrabbit** [comment]
elementary doesn't ship application specific icons. If Geary is using custom icons outside of the freedesktop icon name spec, they should bundle them in a gresource

Closing as "Out of scope"
