### ISSUE TITLE
dialog-password is too similar to the 1Password logo

### ISSUE THREAD

**Issue by SixFingeredAmish** [elementary/icons#639]
Hi there,

The dialog-password icon is too visually similar to 1Password, perhaps we should change it? I think a shield or a wall would work as the new metaphor.

dialog-password
![image](https://user-images.githubusercontent.com/2727095/44429096-31b6e480-a54b-11e8-94d9-ea6da9362924.png)

1Password
![image](https://user-images.githubusercontent.com/2727095/44429083-282d7c80-a54b-11e8-94b9-03174b7a04b1.png)

**Comment by danrabbit** [comment]
I would be interested in making a change to the keyhole shape in particular to match the symbolic version. I think it's more recognizable at small sizes also:

![screenshot from 2018-08-21 14 30 39 2x](https://user-images.githubusercontent.com/7277719/44430222-ddadff00-a54e-11e8-8dfc-8a0164217032.png)

**Comment by danrabbit** [comment]
Leaving here a few candidate revisions that design team was discussing

![screenshot from 2018-08-21 15 19 11 2x](https://user-images.githubusercontent.com/7277719/44432917-eb688200-a558-11e8-9383-7d0f1447f5c1.png)

**Comment by SixFingeredAmish** [comment]
It seems like the inner circle is shifted upwards which makes the icon look unbalanced. Is there is reason the inner circles aren't in the same place like this?

![image](https://user-images.githubusercontent.com/2727095/44433340-bceba680-a55a-11e8-80bd-5309d3c8d53b.png)

**Comment by danrabbit** [comment]
@SixFingeredAmish if you think about what's the purpose of that recessed area, it's to guide the key into the hole. So if it doesn't align with the hole, then you've got kind of a nonsensical design

**Comment by SixFingeredAmish** [comment]
You're right

**Comment by NikoKrause** [comment]
About this icon shape:
![keyhole](https://user-images.githubusercontent.com/7277719/44430222-ddadff00-a54e-11e8-8dfc-8a0164217032.png)

The Signal messenger used to have this icon in the past:
![old signal icon](https://www.pc-magazin.de/bilder/118527686/800x480-c2/signal-private-messenger.jpg)

It always reminded me of the moustache from the main character of the book/movie "Look who's back".
![Look who's back](https://images-na.ssl-images-amazon.com/images/I/31aOH9Wv1qL._SX309_BO1,204,203,200_.jpg)

**Comment by alexeyten** [comment]
https://www.google.com/search?q=keyhole&tbm=isch
It's a very recognizable icon.
