### ISSUE TITLE
File icon

### ISSUE THREAD

**Issue by ItsPossibleAlready** [elementary/icons#641]
![2018-08-24 21-27-02](https://user-images.githubusercontent.com/26849971/44593338-ec154880-a7e4-11e8-88d9-32c2d57d4990.png)
I think color of File must change to this:
****||****
        ****v****
![2018-08-24 21-30-54](https://user-images.githubusercontent.com/26849971/44593404-10712500-a7e5-11e8-873c-44f1a897f103.png)

**Comment by cassidyjames** [comment]
The difference in color is intentional; system apps like Files and System Settings use the neutral silver color.

**Comment by ItsPossibleAlready** [comment]
But System Settings icon is white
