### ISSUE TITLE
New Mail Archive icon

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#66]
the grey file cabinet is kind of dull and it seems that the box is more popular.

Maybe something with the shape kinda like this: 
![files-archive-box](https://cloud.githubusercontent.com/assets/7277719/12879690/01d066da-cdec-11e5-8459-bca9c4dfe2a5.jpg)

But with colors more like this: 
![drawer-archive-icon](https://cloud.githubusercontent.com/assets/7277719/12879693/0904b960-cdec-11e5-9965-56814ad3bd04.png)

**Comment by snwh** [comment]
Fixed with ecb8a12ec65e461f7c2b23ad950128a70c78f41b
