### ISSUE TITLE
Show Desktop icon bug

### ISSUE THREAD

**Issue by btd1337** [elementary/icons#660]
Sometimes occurs this bug in the Show Desktop icon.

Before:
![captura de tela de 2018-09-13 15-38-26](https://user-images.githubusercontent.com/11943860/45508656-b7553b00-b76b-11e8-9b4f-e5603b454b57.png)

Durig mouse hover:
![captura de tela de 2018-09-13 15-38-46](https://user-images.githubusercontent.com/11943860/45508690-d227af80-b76b-11e8-9696-c247b81bd93e.png)

After:
![captura de tela de 2018-09-13 15-38-52](https://user-images.githubusercontent.com/11943860/45508712-e4a1e900-b76b-11e8-97cc-7b8209e439d0.png)

**Comment by danrabbit** [comment]
elementary doesn't ship with a launcher for "Show desktop". Can you provide more information about what provides this launcher?

**Comment by btd1337** [comment]
@danrabbit Plank docklets

![captura de tela de 2018-09-13 19-16-33](https://user-images.githubusercontent.com/11943860/45518938-9e5b8280-b789-11e8-88fe-2bc09b7c5816.png)

**Comment by btd1337** [comment]
Solved in last update.
