### ISSUE TITLE
New folder icons should be easy to generate by apps

### ISSUE THREAD

**Issue by skewty** [elementary/icons#665]
https://gitlab.freedesktop.org/freedesktop/freedesktop/issues/78

**Comment by Djaler** [comment]
I've been waiting for this for a very long time

**Comment by danrabbit** [comment]
Applications are not supposed to make top-level folders in the home directory. According to the freedesktop spec, they should place any local files in `.local/share/` which is a hidden directory.

I think I'm going to close this as a "Design conflict" until that recommendation changes.

**Comment by skewty** [comment]
Not even the Gnome developers were able to follow this recommendation as Gnome Builder creates a Projects folder in ~.  :disappointed:

**Comment by danrabbit** [comment]
@skewty I think what would probably make more sense in this very special case is to submit a pull request to the XDG special dirs spec to add a "Projects" folder since this is a generic toplevel folder that more apps could probably use and benefit from

**Comment by Djaler** [comment]
It also would be cool to have "cloud" dir.
