### ISSUE TITLE
download folder is too small

### ISSUE THREAD

**Issue by hdatma** [elementary/icons#692]
Following the attached screenshot, you see two docks: the bottom one is macos as a reference. The downloads icon on the top dock is elementary's own. As you can see, the icon looks small, and the down arrow in it is almost unreadable. 

![downloads](https://user-images.githubusercontent.com/1321219/46402839-5ed0e800-c6f0-11e8-8d45-c21e0b8dfa95.png)

**Comment by cassidyjames** [comment]
I am not sure what size and dock settings you have going on, but the actual Downloads folder icon is consistent with the other icons in elementary OS. And the folders were recently reworked with higher contrast.

**Comment by danrabbit** [comment]
This looks like the 32px size. I can confirm that in master the symbol on this icon is larger and higher contrast: https://github.com/elementary/icons/blob/master/places/32/folder-download.svg
