### ISSUE TITLE
appointment-soon and appointment-missed

### ISSUE THREAD

**Issue by dahenson** [elementary/icons#694]
It appears we are missing `appointment-soon` and `appointment-missed`. I first saw this in the Calendar notification:
![screenshot from 2018-10-10 13 31 00](https://user-images.githubusercontent.com/2007067/46759586-64e93a80-cc95-11e8-8b85-0941c4089449.png)

There is currently a bug where notifications are not shown at the correct time, but once that is fixed this will be a much bigger issue.

**Comment by danrabbit** [comment]
Looks like it's falling back to "appointment" which is only available in actions/16. We should probably symlink all the icon sizes for the clock from "categories/preferences-system-time" and then add the missing icons to status. The appointment icons are part of the fd.o naming spec
