### ISSUE TITLE
New graphic for top of the README

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#7]
The icons are pretty, but a legit single graphic with some icons that sort of represent the whole set might be nicer than the several icons whose spacing we have no control of.
##

**Comment by danrabbit** [comment]
Originally we had the blue folder. Could do like:
![icons](https://cloud.githubusercontent.com/assets/7277719/11648520/42debebc-9d2a-11e5-95f7-2b161cfa01ec.png)

**Comment by btkostner** [comment]
If we want to do a full width image, the width should be 888px. It will also scale down on mobile devices.

**Comment by TraumaD** [comment]
How about something like this?

![icons_banner](https://user-images.githubusercontent.com/10608836/35449697-5f09440c-0283-11e8-860f-e12b8b79e383.png)

I tried to express the user's and developer's paths when using elementary with the icons while also choosing icons with varied and unique shapes. This in hopes that it will show that the icon set is not just circles and squares and encourage others to make unique silhouetted icons as well.
