### ISSUE TITLE
list-add-symbolic at 24px

### ISSUE THREAD

**Issue by ItsPossibleAlready** [elementary/icons#700]
list-add-symbolic at 24px is blur
![2018-10-16 11 08 11](https://user-images.githubusercontent.com/26849971/46993941-e0366a80-d133-11e8-8fa1-1c514e75597c.png)

**Comment by NikoKrause** [comment]
Symbolic icons are only provided as 16px icon. If you scale it with 1.5 it's probably gonna be blurry.

**Comment by ItsPossibleAlready** [comment]
Yep it hard to scale 1.5x. I close this issue (If it fixable, I can reopen this)
