### ISSUE TITLE
view-fullscreen icon issues

### ISSUE THREAD

**Issue by arshubham** [elementary/icons#702]
Color icon looks blurry at 128px
![image](https://user-images.githubusercontent.com/14235191/47095793-8759f580-d24b-11e8-9a43-d4d5a73c7dfe.png)

Also symbolic icon is same as maximize icon, which leads to confusing ui in some apps like - gnome mpv
![image](https://user-images.githubusercontent.com/14235191/47095954-da33ad00-d24b-11e8-9fab-890985cc9380.png)

Here the formar button is for full screen and later is system button for maximize.

For reference - This is how solus handles the icon: 
![image](https://user-images.githubusercontent.com/14235191/47096075-123af000-d24c-11e8-90f7-2ba367c326a4.png)

**Comment by santileortiz** [comment]
That icon is not from elementary's theme, its from Gnome's, sadly it only comes in sizes 16, 22, 24, 32 and 48 pixels, so displaying it as 128 will be the 48 pixel version but scaled up. As it is a png icon it will be pixelated at that size.

**Comment by Blast-City** [comment]
Hi.

EOG also suffers from this issue. The fullscreen icon is equal to the maximize icon which makes the app look like it has a bug.

Is there a reason why the fullscreen looks like this?

Thanks.
