### ISSUE TITLE
inconsistent go- icons

### ISSUE THREAD

**Issue by artemanufrij** [elementary/icons#708]
![screenshot von 2018-10-26 19 52 37](https://user-images.githubusercontent.com/16517095/47586914-b1a16680-d961-11e8-8318-c3545fef307c.png)

**Comment by micahilbery** [comment]
I believe this is a duplicate of #246 and if not probably ties into it.

**Comment by artemanufrij** [comment]
yeah... looks similar...

**Comment by santileortiz** [comment]
Something strange is going on with the 64px icon.

![screenshot from 2018-10-31 16 54 47](https://user-images.githubusercontent.com/5739220/47821229-02340d80-dd2e-11e8-884f-73a8f3c71aa4.png)

There is no 64px so the logical thing would be to scale the 48px, maybe this is a Gtk/Lookbook issue?
