### ISSUE TITLE
No icons for FocusWriter

### ISSUE THREAD

**Issue by mknepper** [elementary/icons#710]
![focuswriter](https://user-images.githubusercontent.com/12740958/47824880-ee43d800-dd3c-11e8-8f0c-dc18fe99b075.png)

I can't seem to get this to show Focuswriter's icon in the panel. It shows up in the menu for office, but not in the panel. Not sure how to fix this.

**Comment by peteruithoven** [comment]
What panel? 
What are you showing in your screenshot? 
What OS are you running?

I'm pretty sure this has nothing to do with the icon set from elementary OS.

**Comment by peteruithoven** [comment]
Thanks for the clarifications. So I'm assuming you're referring to this project: https://www.xfce-look.org/p/1015802/
I can't find the source of that project.

Oh wait, I think you've opened an issue here: https://github.com/shimmerproject/elementary-xfce/issues/133
Glad you've found it. Good luck with the issue.

**Comment by mknepper** [comment]
Thanks! Sorry to put the issue in the wrong place. Your team does great work. Thanks!
