### ISSUE TITLE
Inconsistent disabled state?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/icons#716]
The following icons all represent disabled things. Shouldn't we find a more consistent visual language for a disabled state?

![screenshot from 2018-11-02 10 21 02](https://user-images.githubusercontent.com/523210/47906711-20af1b80-de8a-11e8-82b6-78da44474769.png)
![screenshot from 2018-11-02 10 19 49](https://user-images.githubusercontent.com/523210/47906712-2147b200-de8a-11e8-8683-003e2f567336.png)

(The microphone is one of the worst offenders, since in the wingpanel icon it doesn't change it's appearance at all. I've opened a separate issue for that one: https://github.com/elementary/icons/issues/717)

When we agree I can open separate more specific issues.

**Comment by peteruithoven** [comment]
@danrabbit has implemented a muted microphone icon in record speed. 
I've split this issue up in:
- Disabled wireless inconsistent? #719 
- Disabled / muted sound inconsistent? #720

**Comment by waldyrious** [comment]
> `@danrabbit` has implemented a muted microphone icon in record speed.

For reference, that was #718.
