### ISSUE TITLE
Disabled wireless inconsistent?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/icons#719]
All the recently updated / added disabled icons feature a slash (NW/SE) through them. The disabled wireless however breaks with this:
![screenshot from 2019-02-12 14-25-43](https://user-images.githubusercontent.com/523210/52638459-507eae00-2ed2-11e9-8d7c-cd195e1010df.png)

Shouldn't the wireless disabled icon also feature the same slash?

One other detail is that the line width of the current icon is very thin compared to other lines, maybe it should be thicker? Or maybe, when we switch to the slash we can use the 3 lines / bars the icon normally features?

Split of from: https://github.com/elementary/icons/issues/716

**Comment by peteruithoven** [comment]
A further improvement / bonus would be to animate the disable. Example of animated disable bluetooth icon: https://github.com/elementary/icons/pull/372/files ([usage in code](https://github.com/elementary/wingpanel-indicator-bluetooth/pull/30))

**Comment by danrabbit** [comment]
something to remember is to distinguish between wireless disabled and wireless disconnected
