### ISSUE TITLE
Disabled / muted sound inconsistent?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/icons#720]
All the recently updated / added disabled icons feature a slash (NW/SE) through them. The disabled / muted sound however breaks with this:
![screenshot from 2019-02-12 14-25-43](https://user-images.githubusercontent.com/523210/52638391-2d53fe80-2ed2-11e9-8584-9e3568ae06b8.png)

Shouldn't the muted / disabled sound icon also feature the same slash?

One downside is that this would have a big effect on the "balance" of the icon, where the cross was positioned in the area where the volume bars where, this area would become empty, which might created inconsistent visual margins. 

Split of from: https://github.com/elementary/icons/issues/716

**Comment by waldyrious** [comment]
Perhaps the volume bars could be outlined as the wireless icon is in the screenshot above? That might help preserve the balance.

**Comment by peteruithoven** [comment]
A further improvement / bonus would be to animate the disable. Example of animated disable bluetooth icon: https://github.com/elementary/icons/pull/372/files ([usage in code](https://github.com/elementary/wingpanel-indicator-bluetooth/pull/30))
