### ISSUE TITLE
@3x assets

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#74]
HiDPI displays are [coming out now](http://www.razerzone.com/store/razer-blade-stealth) that make sense at 3x scaling. We should go ahead and add @3x assets into the icon set...

**Comment by cassidyjames** [comment]
@danrabbit is this something we could do with a precommit hook now that we're in git? :open_mouth:

**Comment by danrabbit** [comment]
No :p We just need to add symlinks for all the folders and add all those folders to index.theme like we did with 2x. It's just a load of shitwork

**Comment by NikoKrause** [comment]
Hey, this seems to be very easy now with cmake.
Just change the line: `set (DPI_ARRAY 1 2)` to `set (DPI_ARRAY 1 2 3)`  here: https://github.com/elementary/icons/blob/master/CMakeLists.txt#L18-L20
