### ISSUE TITLE
Symbolic icons for files and mail

### ISSUE THREAD

**Issue by Mar-tin-W** [elementary/icons#745]
I think the colored icons of the file browser, mail client, etc. are distracting and therefore should be replaced with symbolic ones. 

Sorry I'm not familiar with layouting on GitHub

**Example Mail:**

Elementary:
![screenshot from 2018-12-26 17-39-29](https://user-images.githubusercontent.com/20623262/50451744-2c710880-0936-11e9-8137-3aa45079f016.png)
Applemail:
![screenshot from 2018-12-26 18-05-58](https://user-images.githubusercontent.com/20623262/50452276-6d1e5100-0939-11e9-998b-2ff30ad38599.png)
Mailspring:
![screenshot from 2018-12-26 18-07-03](https://user-images.githubusercontent.com/20623262/50452297-8f17d380-0939-11e9-95dd-019b1c71a589.png)

**Example file browser:**

Elementary:
![screenshot from 2018-12-26 17-42-53](https://user-images.githubusercontent.com/20623262/50451747-33981680-0936-11e9-9f95-e553d4c06302.png)

Ubuntu 18.04:
![screenshot from 2018-12-26 18-14-42](https://user-images.githubusercontent.com/20623262/50452418-398ff680-093a-11e9-8b50-1e755c7b2d6a.png)

VS ubuntu before:
![screenshot from 2018-12-26 18-17-48](https://user-images.githubusercontent.com/20623262/50452501-af945d80-093a-11e9-8810-40bce6d2a1dc.png)

**Comment by waldyrious** [comment]
I'm not sure I agree. Color in icons make them more readily distinguishable, and therefore may reduce usage friction a tiny bit, which, over continued usage, would accumulate to significant amounts.

**Comment by danrabbit** [comment]
I'm going to close this as "Out of scope" for this repo since there's nothing that can be done here to change which icons are requested by apps. If you'd like to make an argument for changing the icon style in a particular app, feel free to open a new issue against that app
