### ISSUE TITLE
Looking for the maximize button icon

### ISSUE THREAD

**Issue by NeoMahler** [elementary/icons#748]
I know this is not a support forum, but I was directed here from [StackExchange](https://elementaryos.stackexchange.com/questions/17772/where-can-i-find-the-maximize-icon-file/17782#17782). I need the maximize icon file and I can't find it anywhere, not in this repo nor in the gtk theme folder. Where is it?

Thanks in advance.

**Comment by cassidyjames** [comment]
The app [LookBook](https://appcenter.elementary.io/com.github.danrabbit.lookbook/) is a great resource for finding semantic icons. Using Github's built-in search or “jump to file” features are also super handy. But I believe you are looking for `maximize-window-symbolic`: https://github.com/elementary/icons/blob/master/actions/symbolic/window-maximize-symbolic.svg
