### ISSUE TITLE
Missing multitasking icon

### ISSUE THREAD

**Issue by gmikhail** [elementary/icons#749]
The icon was in Loki 0.4.1 but missing in Juno 5.

![2019-01-03 172659](https://user-images.githubusercontent.com/4838367/50698676-34276000-104e-11e9-91e8-997eb7b02c05.png)

**Comment by danrabbit** [comment]
Closing as "Out of Scope" for icons. This is a locale-specific issue with Gala's translations

**Comment by gmikhail** [comment]
> This is a locale-specific issue with Gala's translations

I did not quite understand about translation. I mean, instead of multitasking icon uses the standard dummy icon. The icon does not depend on the translation, in all locales it looks the same.

Loki 0.4.1
![1](https://user-images.githubusercontent.com/4838367/50702151-bf0d5800-1058-11e9-8b73-4890ab5a0de6.png)

Juno 5 (dummy icon)
![2](https://user-images.githubusercontent.com/4838367/50702174-cc2a4700-1058-11e9-8a5b-95d9cd0bb691.png)

As for me, the bug is pretty obvious.
