### ISSUE TITLE
Text alignment actions

### ISSUE THREAD

**Issue by danirabbit** [elementary/icons#762]
- [ ] align-horizontal-baseline
- [ ] align-horizontal-baseline-symbolic
- [ ] align-vertical-baseline
- [ ] align-vertical-baseline-symbolic

see http://wiki.inkscape.org/wiki/index.php/Themable_icons

**Comment by Fatih20** [comment]
https://drive.google.com/open?id=1qW9auzREZT_tCmdkJvH7hD66tkgvQueh
Perhaps a baseline for you to work with?

**Comment by Fatih20** [comment]
@danrabbit I would like to work on this and other https://github.com/elementary/icons/projects/2#card-16716782.

**Comment by danrabbit** [comment]
@Fatih20 feel free to submit pull requests :)

**Comment by wpkelso** [comment]
Fixed in #968
