### ISSUE TITLE
Missing boolean operations icons

### ISSUE THREAD

**Issue by Alecaddd** [elementary/icons#765]
Currently missing a full set of icons for boolean operations like:

- [ ] Union
- [ ] Subtract
- [ ] Intersect
- [ ] Difference

Here's a reference from Sketch:
![bool](https://user-images.githubusercontent.com/2527103/51659779-78789280-1f60-11e9-86c6-b318bc173987.jpg)

And these are the symbolic icons I'm working on, still not properly aligned and matching the elementary style:
![bool-symbolic](https://user-images.githubusercontent.com/2527103/51659790-7f070a00-1f60-11e9-8614-7e5f284710b7.png)

**Comment by danrabbit** [comment]
There are a few of these in the set:
* selection-combine (union)
* selection-exclude (difference)
* selection-break

I'm not sure where these icon names comes from. The [inkscape spec](http://wiki.inkscape.org/wiki/index.php/Themable_icons) uses better icon names imo which are:
- [ ] path-union
- [ ] path-difference
- [ ] path-intersection
- [ ] path-exclusion

plus some others
- [ ] path-cut
- [ ] path-division
- [ ] path-combine
- [ ] path-break-apart

**Comment by Alecaddd** [comment]
Oh nice, we already have something like that, sorry I didn't find them.

How icons are named is not a problem, as far as there's consistency in it.
Usually, these operations have always been grouped under the `bool` umbrella, but they can also be grouped under the `path` umbrella since they will actually manipulate the path of an object.
I think would be better to rename or create a symlink for the currently available icons as:
- selection-combine => path-union
- selection-exclude => path-difference
- selection-break => path-break-apart

In terms of visuals, I'd suggest to not use different shapes to represent the operations (eg. union between a square and a circle).
It adds visual complexity to the small icon which is not necessary and makes it harder to remember.

**Comment by danrabbit** [comment]
I think I still like the Tango-style different shapes tbh

![screenshot from 2019-01-24 09 57 09 2x](https://user-images.githubusercontent.com/7277719/51698104-4138ce80-1fbe-11e9-8356-ba439f7fbf22.png)
