### ISSUE TITLE
Icon Browser

### ISSUE THREAD

**Issue by TheNightmanCodeth** [elementary/icons#766]
I think developers would benefit from an online icon browser. I'm thinking about starting work on an unofficial one if this is outside of the project scope but I know I, personally, find it difficult to find an icon that fits where I need it. Especially with symbolic icons, I waste a lot of time scanning through the icon names, opening the preview and going back and trying again. 

A good example is the [material design icon browser](https://material.io/tools/icons/?style=baseline).

**Comment by danrabbit** [comment]
I think I'm going to close this for this repo since it's kind of out of scope for what this repo provides, but you can always check out [LookBook](https://appcenter.elementary.io/com.github.danrabbit.lookbook/) for a native icon browser
