### ISSUE TITLE
Layout icon

### ISSUE THREAD

**Issue by Alecaddd** [elementary/icons#774]
An icon to represent the layout of the application could be useful as a button to open a `Gtk.Popover` and have various options to handle grid, guides, hide/show layout, etc.

Here's a quick example I did:
![layout svg](https://user-images.githubusercontent.com/2527103/51784588-eb6c3f80-20ff-11e9-89de-ee41bf5765e3.png)

And this is what sketch uses:
![screenshot from 2019-01-26 00-14-54](https://user-images.githubusercontent.com/2527103/51784591-f2934d80-20ff-11e9-9171-6d17503de613.png)

**Comment by micahilbery** [comment]
What naming would make the most sense for this icon?

**Comment by micahilbery** [comment]
I imagine it would go in the `actions` directory but would it make the most sense to be named something like `application-layout`, `object-layout`, `window-layout`, ect. or just `layout`

**Comment by danrabbit** [comment]
I kind of wonder if this should be shipped with Akira since this seems pretty specific. I'm not sure there's other apps that are needing this kind of icon at the moment

**Comment by danrabbit** [comment]
I'm gonna go ahead and close this since I don't think we ever found other examples of apps using this pattern. It's probably best to ship this with Akira for now and if we can find wider spread use of this pattern we can evaluate for inclusion then
