### ISSUE TITLE
Create memory symbolic icon

### ISSUE THREAD

**Issue by Dirli** [elementary/icons#783]
Could you create an memory symbolic icon for display on the panel (system monitor indicator)
Thanks you)

**Comment by hezral** [comment]
I'd like to try this. But not sure i understand what "memory" means here :)

**Comment by Dirli** [comment]
ram, so that the user watching it understood what is meant by the consumed memory

**Comment by Dirli** [comment]
https://github.com/Dirli/pantheon-monitor/blob/master/data/screenshot3.png
