### ISSUE TITLE
Create img Icon

### ISSUE THREAD

**Issue by arshubham** [elementary/icons#789]
Currently it only shows a blank icon.
![image](https://user-images.githubusercontent.com/14235191/54869497-3bdde180-4dbf-11e9-85a6-e27a019e49d8.png)

Mimetype: application/x-raw-disk-image

**Comment by leo-sasseron** [comment]
I made this one, but i don't know how to submit it. 
![Image](https://user-images.githubusercontent.com/25991578/55887042-33d5be00-5b83-11e9-8b74-813c0ca50e78.png)

**Comment by vitalkanev** [comment]
@leo-sasseron that's not the correct one.

**Comment by jeremypw** [comment]
The mime-type "application/x-raw-disk-image.xml" is not installed by default but is installed by e.g. Furius Iso Mount Tool.  However the file installed by this app does not specify an icon to use for this mime type and no icons are installed in the hicolor theme, at least by this application.  It is possible that another application installs all the relevant files and updates the caches, in which case the Files PR#1006 will cause Files to show the mime-type icon. 

Are you suggesting that this mime-type and the related icons should be installed "out of the box"?
