### ISSUE TITLE
System Indicators scaling is not uniform; volume shows too big compared with Wi-Fi

### ISSUE THREAD

**Issue by ariebh** [elementary/icons#800]
This is really pedantic but once you see it you can't unsee. 

I'm running Juno on the Huawei MateBook X Pro which has a screen resolution of 3000 X 2000.

![Screenshot from 2019-06-11 17 44 56@2x](https://user-images.githubusercontent.com/48895734/59246944-f6200f00-8c71-11e9-9cbd-ee7ca30b59ce.png)

![markup](https://user-images.githubusercontent.com/48895734/59247811-adb62080-8c74-11e9-807f-2c338b2e01fe.png)

*This is the first issue I have ever logged using Github, sorry if I've done it wrong!

**Comment by Mau-G** [comment]
I think the volume icon is fine. Wifi icon has margins that should be removed so that it matches the height of the other icons

**Comment by ariebh** [comment]
> I think the volume icon is fine. Wifi icon has margins that should be removed so that it matches the height of the other icons

You're right, the Wifi icon is of more immediate concern here, however, I still think the volume icon would still benefit from redesign. It looks out of place amongst the other icons but I'm having trouble identifying just what sets it apart. Maybe it is too wide, or maybe it has something to do with the scale of the actual speaker cone compared with it's sound waves. Maybe it's just my subjective opinion but either way that is for another issue.
