### ISSUE TITLE
Please consider adding an icon for .kdbx files

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/icons#808]
To my understanding and knowledge this is a very common file format for password manager databases. Currently Files only shows a sad and not explaining empty grey-white icon. Do you have any idea how to improve this?

**Comment by jeremypw** [comment]
To fix this there needs to be a suitable file in /usr/share/mime/application defining which icon to use for this mime-type. Its not really a Files problem I am afraid (unless you mean that the fallback icon should be improved). I would have thought that an application that uses this file type would insert a suitable file?

**Comment by jeremypw** [comment]
See "/usr/share/mime/applications/x-dbg.xml" for an example.

**Comment by 4jNsY6fCVqZv** [comment]
I know that's not a Files problem. That's why I created the issue at elementary/icons. I can also create it as an issue at KeePassXC. More sustainable would probably be the solution with a super nice fallback icon in elementary OS itself, right? Otherwise numerous apps would have to change something.

**Comment by 4jNsY6fCVqZv** [comment]
>  I would have thought that an application that uses this file type would insert a suitable file?
:(

**Comment by jeremypw** [comment]
@4jNsY6fCVqZv Sorry, for some reason I thought I was on the Files repo :-(.

It seems that KeePass does create the necessary mime file and specifies the icon "application-x-keepassx" and icons of that name are installed in the "hicolor" theme.  But Files (nor another file manager) is using it. I've tried running update-mime-database, gtk-update-icon-cache and update-desktop-database to no avail even after loggiing out and in. 

I notice another 3rd party program has the same problem - and it used to work with mimetype icons in the hicolor theme.

I tried manually copying the keepass icons into the corresponding elementary theme folders and running gtk-update-icon-cache /usr/share/icons/elementary and then it works OK.

**Comment by jeremypw** [comment]
I am not an expert on icon themes, but the problem may be that elementary is not falling back to use the hicolor theme any more?

**Comment by jeremypw** [comment]
Looking at Files code, it seems that the icon is falling back to a generic icon within the elementary theme before looking in the hicolor theme.  This sees to be related to the way Gtk.IconTheme.choose_icon_for_scale () works (now).  I can push a PR forcing a look for the specified icon in the hicolor theme before falling back.

**Comment by jeremypw** [comment]
As it turns out this was a Files issue - probably introduced when some C code handling icon lookup and caching was ported to Vala :-(

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for taking the time to test this out! Do you think https://github.com/elementary/icons/issues/809 and https://github.com/elementary/icons/issues/789
could be related to this issue?

**Comment by jeremypw** [comment]
I think #789 is probably due to the same bug in Files.  There is a different PR submitted that fixes it by symlinking to the hicolor icons but that would have to be done for each missing icon.  I'll check whether my PR fixes it as well.

**Comment by 4jNsY6fCVqZv** [comment]
Thank you, that would be wonderful, if your PR could fix several problems!

**Comment by 4jNsY6fCVqZv** [comment]
@jeremypw Don't you think https://github.com/elementary/os-patches/issues/63 could be related here?

**Comment by jeremypw** [comment]
@4jNsY6fCVqZv Maybe but not directly.  The icon provided by the app should be good enough.

**Comment by 4jNsY6fCVqZv** [comment]
@jeremypw I wonder whether the OpenConnect VPN client is really a separate app in this case, or just an additional plugin for the network manager?
OpenVPN and PPTP are the default options in elementary OS. So these are two independent apps, each with its own icons and dialogs?!

**Comment by jeremypw** [comment]
That is best discussed on the related issue reports.

**Comment by danirabbit** [comment]
Gonna close this since it sounds like this was a Files bug
