### ISSUE TITLE
Desktop

### ISSUE THREAD

**Issue by algabe** [elementary/icons#81]
MyDesktop icon
![screenshot from 2016-03-28 11-27-21](https://cloud.githubusercontent.com/assets/8870023/14084483/257e1bdc-f4d8-11e5-9cd1-be8736bd319c.png)
To
![screenshot from 2016-03-28 11-02-36](https://cloud.githubusercontent.com/assets/8870023/14084430/e93c1480-f4d7-11e5-96f5-4db6388be1ca.png)
Thanks very much! :+1:

**Comment by snwh** [comment]
There is no desktop in elementary OS, so we wouldn't ship a stylized `user-desktop` icon. If the Desktop folder is created it's just a regular directory.
