### ISSUE TITLE
Reader mode icon

### ISSUE THREAD

**Issue by Exalm** [elementary/icons#816]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature

Epiphany has a reader mode icon bundled currently, looking like this:

![Screenshot from 2019-09-28 22-56-07](https://user-images.githubusercontent.com/1510457/65820485-43bc8980-e219-11e9-9987-b7ef546cb3f1.png)

However, it looks out of place in elementary OS:

![Screenshot from 2019-09-28 23-01-48](https://user-images.githubusercontent.com/1510457/65820544-0e646b80-e21a-11e9-8474-4127e749066e.png)

The existing icon in ephy is called `ephy-reader-mode-symbolic`. It's bundled with the app, but it would be nice if elementary icons included a generic reader mode icon so that it can be used instead if available.

**Comment by cassidyjames** [comment]
Trying to think of a sane icon name. Probably like `document-read` or something? It could also be used i.e. in a Markdown app with edit/view options. Unless that's trying to be too clever, and just `document-reader-view` is more explicit.

**Comment by cassidyjames** [comment]
@alcinnz is also using a similar icon in [Odysseus ](https://github.com/alcinnz/Odysseus) fwiw.

**Comment by Exalm** [comment]
`document-read` sounds like it's about read/unread.

**Comment by cassidyjames** [comment]
@Exalm yeah I was wondering that, too. Yay English. :P

**Comment by alcinnz** [comment]
Here's what I'm using in Odysseus, it seems to fit in very nicely: https://iconmonstr.com/book-17-svg/

**Comment by alcinnz** [comment]
`document-reader-view` sounds nice to me.

**Comment by danrabbit** [comment]
It seems like the precedent here is `view-foo` as in `view-dual`, `view-paged`, `view-continuous`, etc. So `view-reader` seems like it would be the most in line with other icon names
