### ISSUE TITLE
More semantic status icon namespace

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#827]
Brought up when talking about #824. We're abusing that namespace pretty hard.

**Comment by GammaGames** [comment]
Some other ideas for badge icons for status and their meaning:

- `+` - additions
- `*` - modifications
- `-` - removals/deleted
- `✔` - verified (or synced for files/folders from cloud api)
- `🗘` - in progress (or syncing for files/folders from cloud api)

I think a basic set of icons would be nice to use across the system for for more uses than just files. If implemented broadly enough they could be used by apps in Plank to show more statuses. If an app running a process in the background couldn't really use a progress bar, it could enable a spinning `🗘` badge instead. I'm sure there could be other uses but I can't think of any off the top of my head.

**Comment by waldyrious** [comment]
Just a heads-up that `🗘` does not show up correctly in my computer. Perhaps a more common symbol like `⇅` or `…` could work better for that.

**Comment by GammaGames** [comment]
That's fair, I just looked up unicode arrows and picked the one I thought would fit the best.

**Comment by cassidyjames** [comment]
@waldyrious that's not really relevant as these will be drawn as icons, not labels.

**Comment by waldyrious** [comment]
Thanks for the clarification @cassidyjames 👍

**Comment by danrabbit** [comment]
After some discussion we landed on these names to replace the user-* icon names we're abusing:

emblem-disabled

emblem-enabled

emblem-mixed

emblem-error

emblem-warning
