### ISSUE TITLE
Possibly problematic usage of absolute paths in symlinks

### ISSUE THREAD

**Issue by decathorpe** [elementary/icons#832]
It looks like RPM really doesn't like absolute paths in symlinks. I'm getting a lot of these errors now:

```
warning: absolute symlink: /usr/share/icons/elementary/actions@2x -> /usr/share/icons/elementary/actions
```

Why are these not created as relative symlinks instead?

**Comment by tintou** [comment]
I don't think that there is any specific reason, patch welcome :slightly_smiling_face:
