### ISSUE TITLE
Invalid AppData component type "icon-theme"

### ISSUE THREAD

**Issue by decathorpe** [elementary/icons#835]
https://github.com/elementary/icons/blob/master/data/icons.appdata.xml.in#L3

This doesn't seem to be an accepted component type, and it fails appdata validation.

```
+ appstream-util validate-relax --nonet (...)/usr/share/metainfo/io.elementary.icons.appdata.xml: FAILED:
? attribute-invalid     : <component> has invalid type attribute
Validation of files failed
```

**Comment by cassidyjames** [comment]
It's a recent addition, but is probably not supported in your version of the AppStream validator. https://www.freedesktop.org/software/appstream/docs/sect-Metadata-IconTheme.html

**Comment by cassidyjames** [comment]
https://github.com/ximion/appstream/issues/67#issuecomment-521997726

**Comment by decathorpe** [comment]
@cassidyjames Apparently your google-fu is more advanced than mine, because I was looking for that exact thing in the specs, but couldn't find it ...

So I opened this: https://github.com/hughsie/appstream-glib/issues/331

Thanks.

**Comment by cassidyjames** [comment]
@decathorpe ha yeah, I had to find it in order to know what type to use in the first place. :smile:
