### ISSUE TITLE
extension icon has stroke on bottom of top circle

### ISSUE THREAD

**Issue by cassidyjames** [elementary/icons#839]
![Screenshot from 2019-11-16 00 44 55@2x](https://user-images.githubusercontent.com/611168/68983490-85c27e80-080b-11ea-89e0-d9a2e8fa4fe5.png)

**Comment by waldyrious** [comment]
Just to make the issue easier to spot, for future reference:

<img width="339" alt="Screenshot 2019-11-17 at 22 55 35" src="https://user-images.githubusercontent.com/478237/69015619-a286bf80-098d-11ea-8af4-cf87d6254738.png">
