### ISSUE TITLE
[$50] Come up with a mime icon for application-x-partial-download [$50]

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#84]
Right now it inherits the archive icon, which feels really inaccurate 
##

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/32810450-come-up-with-a-mime-icon-for-application-x-partial-download).

**Comment by jonnps** [comment]
This is my first PR and Inkscape editing, sorry if is too bad.

![mime](https://cloud.githubusercontent.com/assets/15981500/25784517/c2767014-3344-11e7-9794-7893c9189783.png)

What do you think?

**Comment by donadigo** [comment]
@jonnps I like it, but I think there's some problems with it currently:
* The white border of the icon is cut like in 2/3 of the icon and it looks weird.
* The gray arrow could use some improvements, it currently looks really flat, solid-color. Perhaps you could use one of the arrows that are already present in the icon theme and replace it?

**Comment by jonnps** [comment]
![new](https://cloud.githubusercontent.com/assets/15981500/25785620/a63a81d0-335b-11e7-92e9-8506babbec54.png)

The border was a miss click, what do you think about this arrow?

**Comment by danrabbit** [comment]
I think you're mixing some metaphors here. You've got the history icon featured and then you have a badge which is something that action and application icons have. So you've communicated that this is an application or an action that saves or downloads some kind of history :p 

I think what is wanted for this icon is something that conveys an incomplete or partial download. Maybe using transparency or dashed lines. Maybe a metaphor that indicates progress.

**Comment by danmana** [comment]
![partial-download](https://cloud.githubusercontent.com/assets/498419/25875963/fd5702b8-3522-11e7-8f90-f5bcc17379e7.png)

How about something like this?

**Comment by snwh** [comment]
I'm :-1: on a metaphor that indicates progress. Folks may expect or presume the progress indicated in the icon reflects the actual progress of the download.

**Comment by jonnps** [comment]
I was trying to think in some metaphor for progress that don't "sound too real" for user, but the only thing i could remember was a sand clock.

![last](https://cloud.githubusercontent.com/assets/15981500/25879891/8239fde6-350a-11e7-8c00-7451bc78221e.png)
#

**Comment by snwh** [comment]
The hourglass (aka sand clock :wink:) has the same issue as the progress-arrow.  A metaphor that indicates a partial or incomplete download (since that is what the icon is for) would be more apt, in my view.

**Comment by lewisgoddard** [comment]
A small puzzle with a piece missing?

**Comment by cassidyjames** [comment]
I think a metaphor more like the we used to have on the developer page could work where it's less a finite progress and more a download coming into existence.

![developer icon](https://web.archive.org/web/20160910091437im_/https://elementary.io/images/developer/developer-sketch.svg)

(icon intended to be viewed on a dark background)

**Comment by harveycabaguio** [comment]
![application-x-partial-download](https://user-images.githubusercontent.com/2775325/33391224-fd381490-d4fd-11e7-9876-cec005dca893.png)

Would this work?

**Comment by micahilbery** [comment]
Maybe something like this?
![text-x-partial-download](https://user-images.githubusercontent.com/10608836/37787445-ec4e752a-2dcc-11e8-8c1c-babea722e5ae.png)

**Comment by waldyrious** [comment]
Here's another idea, from [Wikimedia Commons](https://commons.wikimedia.org/wiki/Category:SVG_download_icons): 

![download_pause svg](https://user-images.githubusercontent.com/478237/39822437-7128fe8c-53a2-11e8-887e-9dfbc233d78e.png)

Also, if the final design indeed uses an arrow, it should probably take #246 into account.

**Comment by NikoKrause** [comment]
Keep the archive icon and put a download arrow on it, e.g.:
![partial-download cheser icon theme](https://raw.githubusercontent.com/chekavy/cheser-icon-theme/master/Cheser/256x256/mimetypes/application-x-partial-download.png)

**Comment by s-kostyuk** [comment]
Maybe _something_ like this? Yes, it looks kinda strange, but... just thinking

![untitled](https://user-images.githubusercontent.com/5122578/44161457-0e60e500-a0c6-11e8-8347-e11216a4840d.png)

**Comment by micahilbery** [comment]
![aplication-x-partial-download](https://user-images.githubusercontent.com/10608836/44234156-803f3a00-a16b-11e8-859f-9b7dad8387c6.png)

**Comment by waldyrious** [comment]
@micahilbery I like that! My initial idea was a purely binary (on/off) pattern as in your [previous comment](https://github.com/elementary/icons/issues/84#issuecomment-375392498), but in hindsight there's very little room in the arrow to produce a gradient using dithering alone. The transparency effect you used is probably much more effective. :+1:

**Comment by waldyrious** [comment]
Alternatively, we could apply dithering to the entire arrow, without attempting a gradient -- that might even be closer to the actual partially downloaded data, which IIUC is not guaranteed to be sequential, but I'm not sure it would be clearer or more legible than the transparency gradient version above.

**Comment by waldyrious** [comment]
Here's an attempt at using both dithering and transparency (without a gradient effect):

![partial-download-dithering-transparency](https://user-images.githubusercontent.com/478237/44260543-994bf780-a20c-11e8-9564-f7df8aa9d9d3.png)

**Comment by waldyrious** [comment]
Hey @danrabbit, the opening comment of this issue says:

> Did you help close this issue? Go claim the $50 bounty on Bountysource.

I thought it would be fair to claim part of the bounty as I believe I contributed significantly to the final solution, and also wanted to try out the receiving side of the Bountysource platform, which so far I had only known as a funder.

However, contrary to what the note quoted above led me to believe, a bounty cannot be shared by multiple people, so my claim has started a conflict process where I'm competing with @micahilbery for the full bounty, which wasn't my intention at all!

I'm happy to leave the bounty in its entirety to @micahilbery, since he indeed committed the actual code that ended up merged, but I have a few questions:
1. How has the community handled cases like this in the past -- i.e., of collaborative fixing of an bountied issue?
2. Would splitting bounties would be welcomed if Bountysource supported it
3. Can the message I quoted above could be tweaked to remove the misleading "help close this issue" part, and make it clear that only one claimaint is expected? If so, where should I propose such a change?
4. Why hasn't the Bountysource note in the initial comment been updated to say that the bounty had already been claimed by @micahilbery? Is this something that should be implemented by Bountysource's github integration?

A note to @codygarver, who funded the bounty: feel free to accept @micahilbery's claim. I'd like to leave my claim up for the record, rather than retract it myself, as I belive this to be a limitation of the Bountysource system rather than my claim being invalid.

**Comment by danrabbit** [comment]
@waldyrious If the bounty needs to be split, bountysource support can be contacted to help with this, but usually the bounty goes to whoever made the pull request and the commits. It's ultimately up to backers to decide who to award a bounty to, so this would be up to @codygarver in this case.

Sure there are cases where splitting bounties makes sense and it would be nice if Bountysource handled that.

No, this is part of the BountySource plugin, so this text is generated automatically. You'll have to file an issue report against BountySource for this.

Yup, this text is provided by their plugin, so you'd need to file an issue report there if you'd like it to reflect when a claim has been made

**Comment by waldyrious** [comment]
Thanks for the clarifications, @danrabbit. I'll raise issues 3 and 4 upstream with Bountysource, then.
