### ISSUE TITLE
cursor shadows bleed off the canvas

### ISSUE THREAD

**Issue by danirabbit** [elementary/icons#854]
It looks like in the current cursor sources the shadow often extends outside the bounds of the canvas resulting in hard edges. This affects almost all icons

**Comment by danrabbit** [comment]
@donadigo does drawing the cursor shadow in Gala sound feasible? I think this would probably be the most maintainable and give us consistency across all cursor sizes. What do you think?

**Comment by danirabbit** [comment]
The only thing left to fix here is the zoom icons
