### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by crozbo** [elementary/icons#868]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
In README.md link to elementary color palette is broken - Error 404

## Platform Information

- [ X] I'm using the latest version from git that I've manually compiled
- [ X] I'm using the latest released stable version

**Comment by waldyrious** [comment]
The fix is to change:

```diff
-https://github.com/elementary/icons/blob/master/elementary.gpl
+https://github.com/elementary/icons/blob/master/data/elementary.gpl
```
