### ISSUE TITLE
8px file/folder permission emblems

### ISSUE THREAD

**Issue by aljelly** [elementary/icons#872]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

### Is your feature request related to a problem? Please describe.
I made some simple edits to the emblems shown for file permissions for 8px versions. These could make it viable for Files to show permissions at the lowest zoom level (`smallest`) in List view and for Columns view.

It's currently not possible to obtain this zoom level for List view out of the box but having emblems for this view could possibly help change this.

There's a [few](https://github.com/elementary/files/issues/1211) [issues](https://github.com/elementary/files/issues/1219) listed for Files relevant to this.

### Currently done icons

![emblem-readonly svg](https://user-images.githubusercontent.com/10395308/73863831-939b0500-4838-11ea-9a2b-636e8febe0fc.png)

_Edit_: new circle background version, with lock remade at a lower size:

![emblem-readonly-2-1 svg](https://user-images.githubusercontent.com/10395308/73878197-0cf32180-4852-11ea-984a-02f947d9a0bd.png)

![emblem-unreadable-1-2 svg](https://user-images.githubusercontent.com/10395308/73863841-9695f580-4838-11ea-8b91-8018b4ab376c.png)

SVGs: [8px emblems.zip](https://github.com/elementary/icons/files/4160925/8px.emblems.zip)

(new circle background version: [new-readonly.zip](https://github.com/elementary/icons/files/4161783/new-readonly.zip))

(sorry for the zip)

They are mostly just simple edits of the 16px versions. They're all pixel-fitted. They haven't been vacuumed with Inkscape.

### Preview

![image](https://user-images.githubusercontent.com/10395308/73878159-f8168e00-4851-11ea-852c-ae03847bd614.png)

Previous mockup:

![image](https://user-images.githubusercontent.com/10395308/73853876-790d5f80-4829-11ea-990c-c0dbe178d136.png)

(mockup)

### Notes
- I haven't done the link icon. This is the only other one necessary for the set to be complete, however making a smaller link icon would be much more difficult than what was involved for the other two icons. If you want me to attempt it I could try making one
- Done! ~~I could perhaps try making an even smaller lock symbol and then put a circle background behind it, so it's consistent with the unreadable icon (if that's wanted)~~
- If you want me to send a PR instead I can do so, it was just easier for the moment to attach the icons to an issue (also properly adding this to the icon theme would require editing the `index.theme` to add an 8px size emblems folder)
- Some tweaks could probably be made

**Comment by KomalleanaByzantis** [comment]
Excellent! I assume that the link emblem as well as the Git emblems should be resized as well?
