### ISSUE TITLE
make inkscape depedency optional

### ISSUE THREAD

**Issue by MrMarukesu** [elementary/icons#886]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
since #851 inkscape became a required depedency, making the flatpak-platform fails to build using more recent releases. since it's only used to make the cursors make the depedency optional and only build the cursors if inkscape is installed.

### To Reproduce
1. Change the Flatpak manifest in [elementay/flatpak-platform](https://github.com/elementary/flatpak-platform) to build the latest release
2. try to build
3. flatpak-builder fails because it's don't have inkscape installed

### Expected behavior
build icons skipping the cursors folder (the unique that depends on inkscape)

### Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by alatiera** [comment]
This is the only place where I could find inkscape being executed, are there any more?

https://github.com/elementary/icons/blob/a78e2a393d492da5ca8d4db5ed8ae7d7a441aa56/cursors/meson.build#L96-L120

From an initial look at it, it seems like the kind of thing we could use librsvg (it also provides an `rsvg-convert` binary) for instead to export the icons. This will also probably speedup the proccess.

**Comment by MrMarukesu** [comment]
Since librsvg is already shipped in gnome sdk, the only additional dependency that need to be added to manifest is the xcursorgen.
