### ISSUE TITLE
cursors theme folder v5.3.0

### ISSUE THREAD

**Issue by Pillgar** [elementary/icons#892]
Hello I just upgraded to v5.3 and noticed an issue within the cursor folder.  It appears there's only text files in there that are empty.  I'm using the arch linux version from the community repo, so I'm not sure if this belongs over there.  No error's that I can tell after upgrading either.  For reference 5.2 cursor folder is 5.1mb and v5.3 is 336bytes.

**Comment by cassidyjames** [comment]
It sounds like their packaging isn't building the cursors correctly. They should be built from SVG source.

**Comment by MrMarukesu** [comment]
it's happen building from the source in the latest release too. the cli of inkscape changed for release 1.0 so it's not exporting the pngs anymore

**Comment by cassidyjames** [comment]
Ah, if it has to do with Inkscape, that makes sense. #888 should also resolve it; we may be able to cut a new release since that's a change that fixes an Inkscape API break.

**Comment by danrabbit** [comment]
New release has been made so it’s up to packagers to update :)
