### ISSUE TITLE
Mouse Cursor in FIREFOX fault

### ISSUE THREAD

**Issue by LewisOdam** [elementary/icons#895]
Elementary OS 5.0 Juno. 

Unable to get a screen shot with the mouse cursor in. 
But, when you hover over a link in firefox rather than the nice black hand and finger cursor being displayed you get this old windows 95 looking sideways one instead. Only noticing it in Firefox so far. 

Nothing major, but is consistent over several fresh installs of JUNO :)

**Comment by eaglersdeveloper** [comment]
Was Firefox installed from Snap Store?
