### ISSUE TITLE
[$100] update audio-speakers icon

### ISSUE THREAD

**Issue by danrabbit** [elementary/icons#90]
This is, at this point, one of the oldest icons in the set. It probably needs to be updated.

One of the big questions here is that the perspective is pretty different from other icons. Maybe we should consider a more straight-on design.

Another issue is if the speaker should remain "disembodied". Maybe it should have some kind of case? We should probably consider what kind of speakers people are connecting to their computers. Should it look like one of those hand-held bluetooth speakers or like something from a home audio setup? Should we stick to something that is more iconic even if it's less "realistic"?

**Comment by cassidyjames** [comment]
The disembodied speaker is definitely more "iconic," but I do agree the perspective stands out. If we're to go more realistic, I could picture a fairly nodescript black bookshelf speaker; it's close enough to some computer speakers all the way up to high end home stereo speakers.

**Comment by cassidyjames** [comment]
Something like this is what's in my head :)

![Black bookshelf speakers](http://www.hyperfi.co.uk/images/Denon_SC-M37b.jpg)

**Comment by cassidyjames** [comment]
Something else to consider is that this icon could be used in places that mean sound _input_ in addition to output. Would a mic next to a speaker be too complex?

**Comment by cassidyjames** [comment]
...aaaand re-read the icon name. `icon-speakers`. Derp, no mic needed here. :P

**Comment by codygarver** [comment]
There is a bounty for this issue [on Bountysource](https://www.bountysource.com/issues/34455082-update-audio-speakers-icon).

**Comment by Paragraph64** [comment]
My solution.
![-2](https://cloud.githubusercontent.com/assets/28448710/25773234/93309456-32a4-11e7-9636-1763cd117e4e.jpg)
What do you think?

**Comment by snwh** [comment]
@Paragraph64 well, your icon doesn't follow many aspects of the [elementary style guide for icons](https://elementary.io/docs/human-interface-guidelines#iconography) and the size variations are not properly scaled.
