### ISSUE TITLE
Close Window Icon in Inkscape is Black Under Dark Theme

### ISSUE THREAD

**Issue by Fatih20** [elementary/icons#910]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Under Inkscape dark theme, when you use the system icons, the close window icon looks black, thus aren't visible. This doesn't happen when you set it to use symbolic icons.
Non-symbolic icons :
![image](https://user-images.githubusercontent.com/51940383/86465941-dd8f0500-bd5c-11ea-88db-8beb2f7526f6.png)
Symbolic icons : 
![image](https://user-images.githubusercontent.com/51940383/86466032-13cc8480-bd5d-11ea-9d94-ca47544f4329.png)

### To Reproduce
Already been explained above

### Expected behavior
The latter screenshot

## Platform Information
Please check what applies:
-->
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
I think the problem here is that there is a non-symbolic icon for window-close that is black. Weirdly enough, it doesn't exist for minimize and unmaximize, they only have symbolic icon. I suspect when Inkscape is set to use non-symbolic icons, it uses the symbolic icon for minimize and unmaximize because they don't have a symbolic icons while using non-symbolic icon for the close window. Which explains why this doesn't happen when Inkscape is set to use symbolic icons.

**Comment by Exalm** [comment]
A non-symbolic icon is not recolored, what a surprise ;)

I wonder why is this elementary icons bug and not an Inkscape bug?

**Comment by Fatih20** [comment]
> A non-symbolic icon is not recolored, what a surprise ;)
> 
> I wonder why is this elementary icons bug and not an Inkscape bug?

Right, it seems this also happens with other icon set. I guess it is.
