### ISSUE TITLE
Tint the transparent portion of battery icons

### ISSUE THREAD

**Issue by danirabbit** [elementary/icons#929]
Look how slick that is: https://twitter.com/clayglobal/status/1290618520947097600?s=21

**Comment by hanaral** [comment]
I tried adding more flair to the x48 icon @micahilbery made, and I'm not sure if I should follow through and do the others too. I kinda need some opinions about the gradient and colour change (I thing green conveys that the battery is mostly full better)
![battery-good](https://user-images.githubusercontent.com/58219504/90388236-6947c100-e07f-11ea-805e-78b7a247da2a.png)

**Comment by danrabbit** [comment]
@hanaral I'm digging the bolder gradient. I think it's worth making a pull request against @micahilbery's branch and seeing if you can work together there :)

I would avoid changing the colors for each value in this branch. These are currently synced with the symbolic icons as well and green is intentionally reserved for 100% charged as a success state so you know the computer is ready to be unplugged.

**Comment by danrabbit** [comment]
Gonna reopen this since @hanaral has some suggestions to continue in this direction

Feel free to open a PR for discussion :)

**Comment by danirabbit** [comment]
Closing since this seems solved and there's been no further discussion
