### ISSUE TITLE
All visible system components should get a distinctive icon

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/icons#961]
In the process of developing elementary OS 6, all system components that are listed as installed in AppCenter or elsewhere visible to users should be given a distinctive icon.

![Screenshot1](https://user-images.githubusercontent.com/46536067/95450376-bc3e4600-0955-11eb-8793-c22bf84fb81f.png)
![Screenshot2](https://user-images.githubusercontent.com/46536067/95450382-bd6f7300-0955-11eb-95e6-7e6b94262f5f.png)
![Screenshot3](https://user-images.githubusercontent.com/46536067/95450385-be080980-0955-11eb-9837-4d6d64cc4a34.png)

**Comment by 4jNsY6fCVqZv** [comment]
![Screenshot](https://user-images.githubusercontent.com/46536067/97548491-19627000-19c7-11eb-9f65-1670ba6bc78e.png)

**Comment by danrabbit** [comment]
Thanks for the report. This is not an issue in the icon set. You'll need to report issues for each component that doesn't display an icon

Closing as "out of scope" since this is an issue with appdata for various components and not an issue with the icon set
