### ISSUE TITLE
The microhphone OSD state icons are not representative

### ISSUE THREAD

**Issue by matzipan** [elementary/icons#99]
As per [this](https://bugs.launchpad.net/gala/+bug/1611477) thread:

The icons in the OSD are not a good representation of the state. If I
see the icon in the OSD in the second screenshot, "microphone muted" is
the last thing I am thinking about. Same with the icon in the first
screenshot, which should stand for "microphone unmuted".

They also don't match the style of the icons in speaker mute/unmute.

**Comment by danrabbit** [comment]
closed by #100
